
package wcf.wxpayservice.org.tempuri;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.4 2018-05-18T09:26:36.119+08:00 Generated source
 * version: 3.2.4
 */
public final class IWxPayService_WSHttpBindingIWxPayService_Client
{

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WxPayService");

    private IWxPayService_WSHttpBindingIWxPayService_Client()
    {}

    public static void main(String args[])
        throws java.lang.Exception
    {
        URL wsdlURL = WxPayService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0]))
        {
            File wsdlFile = new File(args[0]);
            try
            {
                if (wsdlFile.exists())
                {
                    wsdlURL = wsdlFile.toURI().toURL();
                }
                else
                {
                    wsdlURL = new URL(args[0]);
                }
            }
            catch (MalformedURLException e)
            {
                e.printStackTrace();
            }
        }

        WxPayService ss = new WxPayService(wsdlURL, SERVICE_NAME);
        IWxPayService port = ss.getWSHttpBindingIWxPayService();

        {
            System.out.println("Invoking noticeOrderTradeSuccess...");
            java.lang.String _noticeOrderTradeSuccess_orderNumber = "";
            wcf.wxpayservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult _noticeOrderTradeSuccess__return = port.noticeOrderTradeSuccess(_noticeOrderTradeSuccess_orderNumber);
            System.out.println("noticeOrderTradeSuccess.result=" + _noticeOrderTradeSuccess__return);

        }
        {
            System.out.println("Invoking getJsApiParameters...");
            java.lang.String _getJsApiParameters_orderNumber = "";
            java.lang.Integer _getJsApiParameters_orderFrom = null;
            wcf.wxpayservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfPayJsApiRequestzDDmiR8T _getJsApiParameters__return = port.getJsApiParameters(
                _getJsApiParameters_orderNumber, _getJsApiParameters_orderFrom);
            System.out.println("getJsApiParameters.result=" + _getJsApiParameters__return);

        }
        {
            System.out.println("Invoking scanCodeCallback...");
            wcf.wxpayservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_wechat_models.ScanCodeCallbackParam _scanCodeCallback_paras = null;
            wcf.wxpayservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfScanCodeCallbackResultzDDmiR8T _scanCodeCallback__return = port.scanCodeCallback(_scanCodeCallback_paras);
            System.out.println("scanCodeCallback.result=" + _scanCodeCallback__return);

        }
        {
            System.out.println("Invoking getAppParameters...");
            java.lang.String _getAppParameters_orderNumber = "";
            java.lang.Integer _getAppParameters_orderFrom = null;
            wcf.wxpayservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfAppPayParameterResponsex2ZDcWkJ _getAppParameters__return = port.getAppParameters(
                _getAppParameters_orderNumber, _getAppParameters_orderFrom);
            System.out.println("getAppParameters.result=" + _getAppParameters__return);

        }

        System.exit(0);
    }

}
