package wcf.wxpayservice.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.springframework.beans.factory.annotation.Autowired;

import com.ry.xk.springbootframe.config.CommonConfig;

/**
 * This class was generated by Apache CXF 3.2.4 2018-05-18T09:26:36.251+08:00 Generated source
 * version: 3.2.4
 */
@WebServiceClient(name = "WxPayService", wsdlLocation = "http://10.0.3.72:17001/Api/WxPayService.svc?wsdl", targetNamespace = "http://tempuri.org/")
public class WxPayService extends Service
{

    @Autowired
    CommonConfig commonConfig;

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "WxPayService");

    public final static QName WSHttpBindingIWxPayService = new QName("http://tempuri.org/", "WSHttpBinding_IWxPayService");
    static
    {
        URL url = null;
        try
        {
            url = new URL("http://10.0.3.72:17001/Api/WxPayService.svc?wsdl");
        }
        catch (MalformedURLException e)
        {
            java.util.logging.Logger.getLogger(WxPayService.class.getName()).log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
                "http://10.0.3.72:17001/Api/WxPayService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WxPayService(URL wsdlLocation)
    {
        super(wsdlLocation, SERVICE);
    }

    public WxPayService(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }

    public WxPayService()
    {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * @return returns IWxPayService
     */
    @WebEndpoint(name = "WSHttpBinding_IWxPayService")
    public IWxPayService getWSHttpBindingIWxPayService()
    {
        return super.getPort(WSHttpBindingIWxPayService, IWxPayService.class);
    }

    /**
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *            Supported features not in the <code>features</code> parameter will have their
     *            default values.
     * @return returns IWxPayService
     */
    @WebEndpoint(name = "WSHttpBinding_IWxPayService")
    public IWxPayService getWSHttpBindingIWxPayService(WebServiceFeature... features)
    {
        return super.getPort(WSHttpBindingIWxPayService, IWxPayService.class, features);
    }

}
