package wcf.omcorderwrapperservice.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-18T10:58:10.094+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IOMCOrderWrapperService")
@XmlSeeAlso({wcf.omcorderwrapperservice.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_services_servicecontract.ObjectFactory.class, ObjectFactory.class, wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub_models.ObjectFactory.class, wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core_common.ObjectFactory.class, wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ObjectFactory.class, wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub.ObjectFactory.class})
public interface IOMCOrderWrapperService {

    @WebMethod(operationName = "CloseExpireOrder", action = "http://tempuri.org/IOMCOrderWrapperService/CloseExpireOrder")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/CloseExpireOrder", output = "http://tempuri.org/IOMCOrderWrapperService/CloseExpireOrderResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceCloseExpireOrderErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/CloseExpireOrderErrorInfoFault")})
    @RequestWrapper(localName = "CloseExpireOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CloseExpireOrder")
    @ResponseWrapper(localName = "CloseExpireOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CloseExpireOrderResponse")
    @WebResult(name = "CloseExpireOrderResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult closeExpireOrder() throws IOMCOrderWrapperServiceCloseExpireOrderErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetProductOrderNumber", action = "http://tempuri.org/IOMCOrderWrapperService/GetProductOrderNumber")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetProductOrderNumber", output = "http://tempuri.org/IOMCOrderWrapperService/GetProductOrderNumberResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetProductOrderNumberErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetProductOrderNumberErrorInfoFault")})
    @RequestWrapper(localName = "GetProductOrderNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductOrderNumber")
    @ResponseWrapper(localName = "GetProductOrderNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductOrderNumberResponse")
    @WebResult(name = "GetProductOrderNumberResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfstring getProductOrderNumber(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub_models.GetProductOrderNumberRequest request
    ) throws IOMCOrderWrapperServiceGetProductOrderNumberErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "UpdateOrderPayUserId", action = "http://tempuri.org/IOMCOrderWrapperService/UpdateOrderPayUserId")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/UpdateOrderPayUserId", output = "http://tempuri.org/IOMCOrderWrapperService/UpdateOrderPayUserIdResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceUpdateOrderPayUserIdErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/UpdateOrderPayUserIdErrorInfoFault")})
    @RequestWrapper(localName = "UpdateOrderPayUserId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOrderPayUserId")
    @ResponseWrapper(localName = "UpdateOrderPayUserIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOrderPayUserIdResponse")
    @WebResult(name = "UpdateOrderPayUserIdResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult updateOrderPayUserId(
        @WebParam(name = "orderNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String orderNumber,
        @WebParam(name = "payUserId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer payUserId
    ) throws IOMCOrderWrapperServiceUpdateOrderPayUserIdErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "AgainCreateOrder", action = "http://tempuri.org/IOMCOrderWrapperService/AgainCreateOrder")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/AgainCreateOrder", output = "http://tempuri.org/IOMCOrderWrapperService/AgainCreateOrderResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceAgainCreateOrderErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/AgainCreateOrderErrorInfoFault")})
    @RequestWrapper(localName = "AgainCreateOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AgainCreateOrder")
    @ResponseWrapper(localName = "AgainCreateOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AgainCreateOrderResponse")
    @WebResult(name = "AgainCreateOrderResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfOrderPayResultdNPiHdpe againCreateOrder(
        @WebParam(name = "orderSection", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_services_servicecontract.AgainOrderSection orderSection
    ) throws IOMCOrderWrapperServiceAgainCreateOrderErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "CloseOrder", action = "http://tempuri.org/IOMCOrderWrapperService/CloseOrder")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/CloseOrder", output = "http://tempuri.org/IOMCOrderWrapperService/CloseOrderResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceCloseOrderErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/CloseOrderErrorInfoFault")})
    @RequestWrapper(localName = "CloseOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CloseOrder")
    @ResponseWrapper(localName = "CloseOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CloseOrderResponse")
    @WebResult(name = "CloseOrderResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult closeOrder(
        @WebParam(name = "param", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub_models.CloseOrderRequest param
    ) throws IOMCOrderWrapperServiceCloseOrderErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "SendFreeOrderSuccessEvent", action = "http://tempuri.org/IOMCOrderWrapperService/SendFreeOrderSuccessEvent")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/SendFreeOrderSuccessEvent", output = "http://tempuri.org/IOMCOrderWrapperService/SendFreeOrderSuccessEventResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceSendFreeOrderSuccessEventErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/SendFreeOrderSuccessEventErrorInfoFault")})
    @RequestWrapper(localName = "SendFreeOrderSuccessEvent", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendFreeOrderSuccessEvent")
    @ResponseWrapper(localName = "SendFreeOrderSuccessEventResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendFreeOrderSuccessEventResponse")
    @WebResult(name = "SendFreeOrderSuccessEventResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfboolean sendFreeOrderSuccessEvent(
        @WebParam(name = "orderNo", targetNamespace = "http://tempuri.org/")
        java.lang.String orderNo
    ) throws IOMCOrderWrapperServiceSendFreeOrderSuccessEventErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "AddOrderStatusChangeLog", action = "http://tempuri.org/IOMCOrderWrapperService/AddOrderStatusChangeLog")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/AddOrderStatusChangeLog", output = "http://tempuri.org/IOMCOrderWrapperService/AddOrderStatusChangeLogResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceAddOrderStatusChangeLogErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/AddOrderStatusChangeLogErrorInfoFault")})
    @RequestWrapper(localName = "AddOrderStatusChangeLog", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddOrderStatusChangeLog")
    @ResponseWrapper(localName = "AddOrderStatusChangeLogResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddOrderStatusChangeLogResponse")
    @WebResult(name = "AddOrderStatusChangeLogResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult addOrderStatusChangeLog(
        @WebParam(name = "log", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub.OrderstatusChangeLog log
    ) throws IOMCOrderWrapperServiceAddOrderStatusChangeLogErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "NoticeOrderTradeSuccess", action = "http://tempuri.org/IOMCOrderWrapperService/NoticeOrderTradeSuccess")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/NoticeOrderTradeSuccess", output = "http://tempuri.org/IOMCOrderWrapperService/NoticeOrderTradeSuccessResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceNoticeOrderTradeSuccessErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/NoticeOrderTradeSuccessErrorInfoFault")})
    @RequestWrapper(localName = "NoticeOrderTradeSuccess", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NoticeOrderTradeSuccess")
    @ResponseWrapper(localName = "NoticeOrderTradeSuccessResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NoticeOrderTradeSuccessResponse")
    @WebResult(name = "NoticeOrderTradeSuccessResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult noticeOrderTradeSuccess(
        @WebParam(name = "orderNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String orderNumber
    ) throws IOMCOrderWrapperServiceNoticeOrderTradeSuccessErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "CreateOrder", action = "http://tempuri.org/IOMCOrderWrapperService/CreateOrder")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/CreateOrder", output = "http://tempuri.org/IOMCOrderWrapperService/CreateOrderResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceCreateOrderErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/CreateOrderErrorInfoFault")})
    @RequestWrapper(localName = "CreateOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOrder")
    @ResponseWrapper(localName = "CreateOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOrderResponse")
    @WebResult(name = "CreateOrderResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfstring createOrder(
        @WebParam(name = "orderSection", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_services_servicecontract.OrderSection orderSection
    ) throws IOMCOrderWrapperServiceCreateOrderErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "NoticeOrderFailure", action = "http://tempuri.org/IOMCOrderWrapperService/NoticeOrderFailure")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/NoticeOrderFailure", output = "http://tempuri.org/IOMCOrderWrapperService/NoticeOrderFailureResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceNoticeOrderFailureErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/NoticeOrderFailureErrorInfoFault")})
    @RequestWrapper(localName = "NoticeOrderFailure", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NoticeOrderFailure")
    @ResponseWrapper(localName = "NoticeOrderFailureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NoticeOrderFailureResponse")
    @WebResult(name = "NoticeOrderFailureResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult noticeOrderFailure(
        @WebParam(name = "orderNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String orderNumber
    ) throws IOMCOrderWrapperServiceNoticeOrderFailureErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "NoticeCallBackSuccess", action = "http://tempuri.org/IOMCOrderWrapperService/NoticeCallBackSuccess")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/NoticeCallBackSuccess", output = "http://tempuri.org/IOMCOrderWrapperService/NoticeCallBackSuccessResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceNoticeCallBackSuccessErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/NoticeCallBackSuccessErrorInfoFault")})
    @RequestWrapper(localName = "NoticeCallBackSuccess", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NoticeCallBackSuccess")
    @ResponseWrapper(localName = "NoticeCallBackSuccessResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NoticeCallBackSuccessResponse")
    @WebResult(name = "NoticeCallBackSuccessResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult noticeCallBackSuccess(
        @WebParam(name = "orderNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String orderNumber
    ) throws IOMCOrderWrapperServiceNoticeCallBackSuccessErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrderPayMode", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrderPayMode")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrderPayMode", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrderPayModeResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrderPayModeErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrderPayModeErrorInfoFault")})
    @RequestWrapper(localName = "GetOrderPayMode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderPayMode")
    @ResponseWrapper(localName = "GetOrderPayModeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderPayModeResponse")
    @WebResult(name = "GetOrderPayModeResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfArrayOfOrderPayModedNPiHdpe getOrderPayMode() throws IOMCOrderWrapperServiceGetOrderPayModeErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrderById", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrderById")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrderById", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrderByIdResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrderByIdErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrderByIdErrorInfoFault")})
    @RequestWrapper(localName = "GetOrderById", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderById")
    @ResponseWrapper(localName = "GetOrderByIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderByIdResponse")
    @WebResult(name = "GetOrderByIdResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfOrderdNPiHdpe getOrderById(
        @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
        java.lang.Long orderId
    ) throws IOMCOrderWrapperServiceGetOrderByIdErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "UpdateOrderPayMode", action = "http://tempuri.org/IOMCOrderWrapperService/UpdateOrderPayMode")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/UpdateOrderPayMode", output = "http://tempuri.org/IOMCOrderWrapperService/UpdateOrderPayModeResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceUpdateOrderPayModeErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/UpdateOrderPayModeErrorInfoFault")})
    @RequestWrapper(localName = "UpdateOrderPayMode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOrderPayMode")
    @ResponseWrapper(localName = "UpdateOrderPayModeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOrderPayModeResponse")
    @WebResult(name = "UpdateOrderPayModeResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResult updateOrderPayMode(
        @WebParam(name = "orderPayTrade", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_services_servicecontract.OrderPayTrade orderPayTrade
    ) throws IOMCOrderWrapperServiceUpdateOrderPayModeErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrderInfoByNumber", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrderInfoByNumber")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrderInfoByNumber", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrderInfoByNumberResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrderInfoByNumberErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrderInfoByNumberErrorInfoFault")})
    @RequestWrapper(localName = "GetOrderInfoByNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderInfoByNumber")
    @ResponseWrapper(localName = "GetOrderInfoByNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderInfoByNumberResponse")
    @WebResult(name = "GetOrderInfoByNumberResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfOrderdNPiHdpe getOrderInfoByNumber(
        @WebParam(name = "orderNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String orderNumber
    ) throws IOMCOrderWrapperServiceGetOrderInfoByNumberErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrderQuantity", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrderQuantity")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrderQuantity", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrderQuantityResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrderQuantityErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrderQuantityErrorInfoFault")})
    @RequestWrapper(localName = "GetOrderQuantity", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderQuantity")
    @ResponseWrapper(localName = "GetOrderQuantityResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderQuantityResponse")
    @WebResult(name = "GetOrderQuantityResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfArrayOfOrderStatusQuantitydNPiHdpe getOrderQuantity(
        @WebParam(name = "param", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub.QueryOrderQuantityParam param
    ) throws IOMCOrderWrapperServiceGetOrderQuantityErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "CheckProductExistsOrder", action = "http://tempuri.org/IOMCOrderWrapperService/CheckProductExistsOrder")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/CheckProductExistsOrder", output = "http://tempuri.org/IOMCOrderWrapperService/CheckProductExistsOrderResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceCheckProductExistsOrderErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/CheckProductExistsOrderErrorInfoFault")})
    @RequestWrapper(localName = "CheckProductExistsOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckProductExistsOrder")
    @ResponseWrapper(localName = "CheckProductExistsOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckProductExistsOrderResponse")
    @WebResult(name = "CheckProductExistsOrderResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfboolean checkProductExistsOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub_models.CheckProductExistsOrderRequest request
    ) throws IOMCOrderWrapperServiceCheckProductExistsOrderErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrderScanCodePayUrl", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrderScanCodePayUrl")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrderScanCodePayUrl", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrderScanCodePayUrlResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrderScanCodePayUrlErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrderScanCodePayUrlErrorInfoFault")})
    @RequestWrapper(localName = "GetOrderScanCodePayUrl", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderScanCodePayUrl")
    @ResponseWrapper(localName = "GetOrderScanCodePayUrlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderScanCodePayUrlResponse")
    @WebResult(name = "GetOrderScanCodePayUrlResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfstring getOrderScanCodePayUrl(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub_models.GetOrderPayUrlRequest request
    ) throws IOMCOrderWrapperServiceGetOrderScanCodePayUrlErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrdersByQueryParams", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrdersByQueryParams")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrdersByQueryParams", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrdersByQueryParamsResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrdersByQueryParamsErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrdersByQueryParamsErrorInfoFault")})
    @RequestWrapper(localName = "GetOrdersByQueryParams", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrdersByQueryParams")
    @ResponseWrapper(localName = "GetOrdersByQueryParamsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrdersByQueryParamsResponse")
    @WebResult(name = "GetOrdersByQueryParamsResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfPageOfOrderdNPiHdpem06JEnuP getOrdersByQueryParams(
        @WebParam(name = "pParams", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub.QueryOrdersParam pParams
    ) throws IOMCOrderWrapperServiceGetOrdersByQueryParamsErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrdersByFilterParams", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrdersByFilterParams")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrdersByFilterParams", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrdersByFilterParamsResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrdersByFilterParamsErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrdersByFilterParamsErrorInfoFault")})
    @RequestWrapper(localName = "GetOrdersByFilterParams", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrdersByFilterParams")
    @ResponseWrapper(localName = "GetOrdersByFilterParamsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrdersByFilterParamsResponse")
    @WebResult(name = "GetOrdersByFilterParamsResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfPageOfOrderdNPiHdpem06JEnuP getOrdersByFilterParams(
        @WebParam(name = "oParams", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub.OrderFilterParam oParams
    ) throws IOMCOrderWrapperServiceGetOrdersByFilterParamsErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "ChangeStatus", action = "http://tempuri.org/IOMCOrderWrapperService/ChangeStatus")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/ChangeStatus", output = "http://tempuri.org/IOMCOrderWrapperService/ChangeStatusResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceChangeStatusErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/ChangeStatusErrorInfoFault")})
    @RequestWrapper(localName = "ChangeStatus", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeStatus")
    @ResponseWrapper(localName = "ChangeStatusResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeStatusResponse")
    @WebResult(name = "ChangeStatusResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean changeStatus(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub_models.ChangeOrderStatusRequest request
    ) throws IOMCOrderWrapperServiceChangeStatusErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrderIsSuccess", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrderIsSuccess")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrderIsSuccess", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrderIsSuccessResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrderIsSuccessErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrderIsSuccessErrorInfoFault")})
    @RequestWrapper(localName = "GetOrderIsSuccess", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderIsSuccess")
    @ResponseWrapper(localName = "GetOrderIsSuccessResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderIsSuccessResponse")
    @WebResult(name = "GetOrderIsSuccessResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfTransactionType5Y56Hjij getOrderIsSuccess(
        @WebParam(name = "queryOrder", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_services_servicecontract.QueryOrderParamSection queryOrder
    ) throws IOMCOrderWrapperServiceGetOrderIsSuccessErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "CreateOmcOrder", action = "http://tempuri.org/IOMCOrderWrapperService/CreateOmcOrder")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/CreateOmcOrder", output = "http://tempuri.org/IOMCOrderWrapperService/CreateOmcOrderResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceCreateOmcOrderErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/CreateOmcOrderErrorInfoFault")})
    @RequestWrapper(localName = "CreateOmcOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOmcOrder")
    @ResponseWrapper(localName = "CreateOmcOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOmcOrderResponse")
    @WebResult(name = "CreateOmcOrderResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfstring createOmcOrder(
        @WebParam(name = "orderSection", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_services_servicecontract.OrderSection orderSection
    ) throws IOMCOrderWrapperServiceCreateOmcOrderErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetExistsOrderByProduct", action = "http://tempuri.org/IOMCOrderWrapperService/GetExistsOrderByProduct")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetExistsOrderByProduct", output = "http://tempuri.org/IOMCOrderWrapperService/GetExistsOrderByProductResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetExistsOrderByProductErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetExistsOrderByProductErrorInfoFault")})
    @RequestWrapper(localName = "GetExistsOrderByProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExistsOrderByProduct")
    @ResponseWrapper(localName = "GetExistsOrderByProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExistsOrderByProductResponse")
    @WebResult(name = "GetExistsOrderByProductResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfOrderdNPiHdpe getExistsOrderByProduct(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub_models.CheckProductExistsOrderRequest request
    ) throws IOMCOrderWrapperServiceGetExistsOrderByProductErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrderScanCodePayShortUrl", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrderScanCodePayShortUrl")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrderScanCodePayShortUrl", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrderScanCodePayShortUrlResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrderScanCodePayShortUrlErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrderScanCodePayShortUrlErrorInfoFault")})
    @RequestWrapper(localName = "GetOrderScanCodePayShortUrl", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderScanCodePayShortUrl")
    @ResponseWrapper(localName = "GetOrderScanCodePayShortUrlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderScanCodePayShortUrlResponse")
    @WebResult(name = "GetOrderScanCodePayShortUrlResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfstring getOrderScanCodePayShortUrl(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_imoduleservices_orderhub_models.GetOrderPayUrlRequest request
    ) throws IOMCOrderWrapperServiceGetOrderScanCodePayShortUrlErrorInfoFaultFaultMessage;

    @WebMethod(operationName = "GetOrderByNumber", action = "http://tempuri.org/IOMCOrderWrapperService/GetOrderByNumber")
    @Action(input = "http://tempuri.org/IOMCOrderWrapperService/GetOrderByNumber", output = "http://tempuri.org/IOMCOrderWrapperService/GetOrderByNumberResponse", fault = {@FaultAction(className = IOMCOrderWrapperServiceGetOrderByNumberErrorInfoFaultFaultMessage.class, value = "http://tempuri.org/IOMCOrderWrapperService/GetOrderByNumberErrorInfoFault")})
    @RequestWrapper(localName = "GetOrderByNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderByNumber")
    @ResponseWrapper(localName = "GetOrderByNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderByNumberResponse")
    @WebResult(name = "GetOrderByNumberResult", targetNamespace = "http://tempuri.org/")
    public wcf.omcorderwrapperservice.org.datacontract.schemas._2004._07.omcsystem_core.ServiceResultOfOrderdNPiHdpe getOrderByNumber(
        @WebParam(name = "orderNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String orderNumber
    ) throws IOMCOrderWrapperServiceGetOrderByNumberErrorInfoFaultFaultMessage;
}
