package wcf.tikuservice.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-19T19:32:58.728+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ITikuService")
@XmlSeeAlso({wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ObjectFactory.class, ObjectFactory.class, wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ObjectFactory.class, wcf.tikuservice.org.datacontract.schemas._2004._07.motk.ObjectFactory.class, wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_exam.ObjectFactory.class})
public interface ITikuService {

    @WebMethod(operationName = "GetExamSetQuestionSection", action = "http://tempuri.org/ITikuService/GetExamSetQuestionSection")
    @Action(input = "http://tempuri.org/ITikuService/GetExamSetQuestionSection", output = "http://tempuri.org/ITikuService/GetExamSetQuestionSectionResponse")
    @RequestWrapper(localName = "GetExamSetQuestionSection", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamSetQuestionSection")
    @ResponseWrapper(localName = "GetExamSetQuestionSectionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamSetQuestionSectionResponse")
    @WebResult(name = "GetExamSetQuestionSectionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree getExamSetQuestionSection(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "bookversionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookversionId,
        @WebParam(name = "online", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean online
    );

    @WebMethod(operationName = "GetKnowledgePointQuestionCount", action = "http://tempuri.org/ITikuService/GetKnowledgePointQuestionCount")
    @Action(input = "http://tempuri.org/ITikuService/GetKnowledgePointQuestionCount", output = "http://tempuri.org/ITikuService/GetKnowledgePointQuestionCountResponse")
    @RequestWrapper(localName = "GetKnowledgePointQuestionCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKnowledgePointQuestionCount")
    @ResponseWrapper(localName = "GetKnowledgePointQuestionCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKnowledgePointQuestionCountResponse")
    @WebResult(name = "GetKnowledgePointQuestionCountResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfKnowledgePointQuestionCount getKnowledgePointQuestionCount(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetQuestionFaultTypes", action = "http://tempuri.org/ITikuService/GetQuestionFaultTypes")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionFaultTypes", output = "http://tempuri.org/ITikuService/GetQuestionFaultTypesResponse")
    @RequestWrapper(localName = "GetQuestionFaultTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionFaultTypes")
    @ResponseWrapper(localName = "GetQuestionFaultTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionFaultTypesResponse")
    @WebResult(name = "GetQuestionFaultTypesResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionFaultType getQuestionFaultTypes();

    @WebMethod(operationName = "GetKnowledgePoints", action = "http://tempuri.org/ITikuService/GetKnowledgePoints")
    @Action(input = "http://tempuri.org/ITikuService/GetKnowledgePoints", output = "http://tempuri.org/ITikuService/GetKnowledgePointsResponse")
    @RequestWrapper(localName = "GetKnowledgePoints", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKnowledgePoints")
    @ResponseWrapper(localName = "GetKnowledgePointsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKnowledgePointsResponse")
    @WebResult(name = "GetKnowledgePointsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.KnowledgePointList getKnowledgePoints(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "SetPreviewConfigSession", action = "http://tempuri.org/ITikuService/SetPreviewConfigSession")
    @Action(input = "http://tempuri.org/ITikuService/SetPreviewConfigSession", output = "http://tempuri.org/ITikuService/SetPreviewConfigSessionResponse")
    @RequestWrapper(localName = "SetPreviewConfigSession", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetPreviewConfigSession")
    @ResponseWrapper(localName = "SetPreviewConfigSessionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetPreviewConfigSessionResponse")
    public void setPreviewConfigSession(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "examConfig", targetNamespace = "http://tempuri.org/")
        java.lang.String examConfig,
        @WebParam(name = "online", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean online
    );

    @WebMethod(operationName = "RemoveQuestion", action = "http://tempuri.org/ITikuService/RemoveQuestion")
    @Action(input = "http://tempuri.org/ITikuService/RemoveQuestion", output = "http://tempuri.org/ITikuService/RemoveQuestionResponse")
    @RequestWrapper(localName = "RemoveQuestion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveQuestion")
    @ResponseWrapper(localName = "RemoveQuestionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveQuestionResponse")
    public void removeQuestion(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "questionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionId
    );

    @WebMethod(operationName = "GetAllPublishers", action = "http://tempuri.org/ITikuService/GetAllPublishers")
    @Action(input = "http://tempuri.org/ITikuService/GetAllPublishers", output = "http://tempuri.org/ITikuService/GetAllPublishersResponse")
    @RequestWrapper(localName = "GetAllPublishers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPublishers")
    @ResponseWrapper(localName = "GetAllPublishersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPublishersResponse")
    @WebResult(name = "GetAllPublishersResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfPublisher getAllPublishers();

    @WebMethod(operationName = "GetQuestionById", action = "http://tempuri.org/ITikuService/GetQuestionById")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionById", output = "http://tempuri.org/ITikuService/GetQuestionByIdResponse")
    @RequestWrapper(localName = "GetQuestionById", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionById")
    @ResponseWrapper(localName = "GetQuestionByIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionByIdResponse")
    @WebResult(name = "GetQuestionByIdResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.Question getQuestionById(
        @WebParam(name = "questionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionId
    );

    @WebMethod(operationName = "GetAllCollectionQuestion", action = "http://tempuri.org/ITikuService/GetAllCollectionQuestion")
    @Action(input = "http://tempuri.org/ITikuService/GetAllCollectionQuestion", output = "http://tempuri.org/ITikuService/GetAllCollectionQuestionResponse")
    @RequestWrapper(localName = "GetAllCollectionQuestion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllCollectionQuestion")
    @ResponseWrapper(localName = "GetAllCollectionQuestionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllCollectionQuestionResponse")
    @WebResult(name = "GetAllCollectionQuestionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView getAllCollectionQuestion(
        @WebParam(name = "bookVersionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookVersionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "pageNumber", targetNamespace = "http://tempuri.org/")
        java.lang.Integer pageNumber,
        @WebParam(name = "numberRecords", targetNamespace = "http://tempuri.org/")
        java.lang.Integer numberRecords,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "online", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean online
    );

    @WebMethod(operationName = "GetCourseMappingIdBySectionId", action = "http://tempuri.org/ITikuService/GetCourseMappingIdBySectionId")
    @Action(input = "http://tempuri.org/ITikuService/GetCourseMappingIdBySectionId", output = "http://tempuri.org/ITikuService/GetCourseMappingIdBySectionIdResponse")
    @RequestWrapper(localName = "GetCourseMappingIdBySectionId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseMappingIdBySectionId")
    @ResponseWrapper(localName = "GetCourseMappingIdBySectionIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseMappingIdBySectionIdResponse")
    @WebResult(name = "GetCourseMappingIdBySectionIdResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer getCourseMappingIdBySectionId(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetCourseMappingIdBySectionIdRequest request
    );

    @WebMethod(operationName = "GetChapterList", action = "http://tempuri.org/ITikuService/GetChapterList")
    @Action(input = "http://tempuri.org/ITikuService/GetChapterList", output = "http://tempuri.org/ITikuService/GetChapterListResponse")
    @RequestWrapper(localName = "GetChapterList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterList")
    @ResponseWrapper(localName = "GetChapterListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterListResponse")
    @WebResult(name = "GetChapterListResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfChapterSectionView getChapterList(
        @WebParam(name = "courseMappingId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseMappingId
    );

    @WebMethod(operationName = "AddQuestionOnClick", action = "http://tempuri.org/ITikuService/AddQuestionOnClick")
    @Action(input = "http://tempuri.org/ITikuService/AddQuestionOnClick", output = "http://tempuri.org/ITikuService/AddQuestionOnClickResponse")
    @RequestWrapper(localName = "AddQuestionOnClick", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddQuestionOnClick")
    @ResponseWrapper(localName = "AddQuestionOnClickResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddQuestionOnClickResponse")
    public void addQuestionOnClick(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "question", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionSimplifiedFormat question,
        @WebParam(name = "bookversionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookversionId
    );

    @WebMethod(operationName = "GenerateAutoZujuanQuestions", action = "http://tempuri.org/ITikuService/GenerateAutoZujuanQuestions")
    @Action(input = "http://tempuri.org/ITikuService/GenerateAutoZujuanQuestions", output = "http://tempuri.org/ITikuService/GenerateAutoZujuanQuestionsResponse")
    @RequestWrapper(localName = "GenerateAutoZujuanQuestions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateAutoZujuanQuestions")
    @ResponseWrapper(localName = "GenerateAutoZujuanQuestionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateAutoZujuanQuestionsResponse")
    @WebResult(name = "GenerateAutoZujuanQuestionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListCategorieCountView generateAutoZujuanQuestions(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_exam.AutoZujuanCreationRequest request
    );

    @WebMethod(operationName = "GetCourseMappings", action = "http://tempuri.org/ITikuService/GetCourseMappings")
    @Action(input = "http://tempuri.org/ITikuService/GetCourseMappings", output = "http://tempuri.org/ITikuService/GetCourseMappingsResponse")
    @RequestWrapper(localName = "GetCourseMappings", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseMappings")
    @ResponseWrapper(localName = "GetCourseMappingsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseMappingsResponse")
    @WebResult(name = "GetCourseMappingsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfCourseMapping getCourseMappings(
        @WebParam(name = "bookVersionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookVersionId
    );

    @WebMethod(operationName = "GetSchoolBookVersion", action = "http://tempuri.org/ITikuService/GetSchoolBookVersion")
    @Action(input = "http://tempuri.org/ITikuService/GetSchoolBookVersion", output = "http://tempuri.org/ITikuService/GetSchoolBookVersionResponse")
    @RequestWrapper(localName = "GetSchoolBookVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSchoolBookVersion")
    @ResponseWrapper(localName = "GetSchoolBookVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSchoolBookVersionResponse")
    @WebResult(name = "GetSchoolBookVersionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfSchoolBookVersion getSchoolBookVersion(
        @WebParam(name = "schoolId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer schoolId
    );

    @WebMethod(operationName = "GetBookVersionQuestionCount", action = "http://tempuri.org/ITikuService/GetBookVersionQuestionCount")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersionQuestionCount", output = "http://tempuri.org/ITikuService/GetBookVersionQuestionCountResponse")
    @RequestWrapper(localName = "GetBookVersionQuestionCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionQuestionCount")
    @ResponseWrapper(localName = "GetBookVersionQuestionCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionQuestionCountResponse")
    @WebResult(name = "GetBookVersionQuestionCountResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer getBookVersionQuestionCount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "SearchQuestions", action = "http://tempuri.org/ITikuService/SearchQuestions")
    @Action(input = "http://tempuri.org/ITikuService/SearchQuestions", output = "http://tempuri.org/ITikuService/SearchQuestionsResponse")
    @RequestWrapper(localName = "SearchQuestions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchQuestions")
    @ResponseWrapper(localName = "SearchQuestionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchQuestionsResponse")
    @WebResult(name = "SearchQuestionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView searchQuestions(
        @WebParam(name = "bookVersionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookVersionId,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        java.lang.String keyword,
        @WebParam(name = "questionLevel", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionLevel,
        @WebParam(name = "questionCategoryId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionCategoryId,
        @WebParam(name = "onlineOnly", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean onlineOnly,
        @WebParam(name = "pageNumber", targetNamespace = "http://tempuri.org/")
        java.lang.Integer pageNumber,
        @WebParam(name = "numberRecords", targetNamespace = "http://tempuri.org/")
        java.lang.Integer numberRecords
    );

    @WebMethod(operationName = "GetQuestionSectionDistribution", action = "http://tempuri.org/ITikuService/GetQuestionSectionDistribution")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionSectionDistribution", output = "http://tempuri.org/ITikuService/GetQuestionSectionDistributionResponse")
    @RequestWrapper(localName = "GetQuestionSectionDistribution", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionSectionDistribution")
    @ResponseWrapper(localName = "GetQuestionSectionDistributionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionSectionDistributionResponse")
    @WebResult(name = "GetQuestionSectionDistributionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfQuestionSectionDistributionView getQuestionSectionDistribution(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionSectionDistributionRequest request
    );

    @WebMethod(operationName = "GetOnlineQuestions", action = "http://tempuri.org/ITikuService/GetOnlineQuestions")
    @Action(input = "http://tempuri.org/ITikuService/GetOnlineQuestions", output = "http://tempuri.org/ITikuService/GetOnlineQuestionsResponse")
    @RequestWrapper(localName = "GetOnlineQuestions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOnlineQuestions")
    @ResponseWrapper(localName = "GetOnlineQuestionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOnlineQuestionsResponse")
    @WebResult(name = "GetOnlineQuestionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.OnlineQuestionSimplifiedFormatSectionList getOnlineQuestions(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetOnlineQuestionsRequest request
    );

    @WebMethod(operationName = "GetBookVersionByCourse", action = "http://tempuri.org/ITikuService/GetBookVersionByCourse")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersionByCourse", output = "http://tempuri.org/ITikuService/GetBookVersionByCourseResponse")
    @RequestWrapper(localName = "GetBookVersionByCourse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionByCourse")
    @ResponseWrapper(localName = "GetBookVersionByCourseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionByCourseResponse")
    @WebResult(name = "GetBookVersionByCourseResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.BookVersion getBookVersionByCourse(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetQuestionsFromCourseMappingAll", action = "http://tempuri.org/ITikuService/GetQuestionsFromCourseMappingAll")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionsFromCourseMappingAll", output = "http://tempuri.org/ITikuService/GetQuestionsFromCourseMappingAllResponse")
    @RequestWrapper(localName = "GetQuestionsFromCourseMappingAll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsFromCourseMappingAll")
    @ResponseWrapper(localName = "GetQuestionsFromCourseMappingAllResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsFromCourseMappingAllResponse")
    @WebResult(name = "GetQuestionsFromCourseMappingAllResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionSimplifiedFormat getQuestionsFromCourseMappingAll(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionsFromCourseMappingAllRequest request
    );

    @WebMethod(operationName = "GetQuestionKnowledgePointDistribution", action = "http://tempuri.org/ITikuService/GetQuestionKnowledgePointDistribution")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionKnowledgePointDistribution", output = "http://tempuri.org/ITikuService/GetQuestionKnowledgePointDistributionResponse")
    @RequestWrapper(localName = "GetQuestionKnowledgePointDistribution", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionKnowledgePointDistribution")
    @ResponseWrapper(localName = "GetQuestionKnowledgePointDistributionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionKnowledgePointDistributionResponse")
    @WebResult(name = "GetQuestionKnowledgePointDistributionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfQuestionKnowledgePointDistributionView getQuestionKnowledgePointDistribution(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionKnowledgePointDistributionRequest request
    );

    @WebMethod(operationName = "GetQuestionsFromKnowledgePointsAll", action = "http://tempuri.org/ITikuService/GetQuestionsFromKnowledgePointsAll")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionsFromKnowledgePointsAll", output = "http://tempuri.org/ITikuService/GetQuestionsFromKnowledgePointsAllResponse")
    @RequestWrapper(localName = "GetQuestionsFromKnowledgePointsAll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsFromKnowledgePointsAll")
    @ResponseWrapper(localName = "GetQuestionsFromKnowledgePointsAllResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsFromKnowledgePointsAllResponse")
    @WebResult(name = "GetQuestionsFromKnowledgePointsAllResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionSimplifiedFormatCache getQuestionsFromKnowledgePointsAll(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionsFromKnowledgePointsAllRequest request
    );

    @WebMethod(operationName = "GetBookVersionInfo", action = "http://tempuri.org/ITikuService/GetBookVersionInfo")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersionInfo", output = "http://tempuri.org/ITikuService/GetBookVersionInfoResponse")
    @RequestWrapper(localName = "GetBookVersionInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionInfo")
    @ResponseWrapper(localName = "GetBookVersionInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionInfoResponse")
    @WebResult(name = "GetBookVersionInfoResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.BookVersion getBookVersionInfo(
        @WebParam(name = "bookVersionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookVersionId
    );

    @WebMethod(operationName = "GetQuestionCategoryById", action = "http://tempuri.org/ITikuService/GetQuestionCategoryById")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionCategoryById", output = "http://tempuri.org/ITikuService/GetQuestionCategoryByIdResponse")
    @RequestWrapper(localName = "GetQuestionCategoryById", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoryById")
    @ResponseWrapper(localName = "GetQuestionCategoryByIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoryByIdResponse")
    @WebResult(name = "GetQuestionCategoryByIdResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.QuestionCategory getQuestionCategoryById(
        @WebParam(name = "categoryId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer categoryId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetHasQuestionBookVersionViewsByCourseId", action = "http://tempuri.org/ITikuService/GetHasQuestionBookVersionViewsByCourseId")
    @Action(input = "http://tempuri.org/ITikuService/GetHasQuestionBookVersionViewsByCourseId", output = "http://tempuri.org/ITikuService/GetHasQuestionBookVersionViewsByCourseIdResponse")
    @RequestWrapper(localName = "GetHasQuestionBookVersionViewsByCourseId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHasQuestionBookVersionViewsByCourseId")
    @ResponseWrapper(localName = "GetHasQuestionBookVersionViewsByCourseIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHasQuestionBookVersionViewsByCourseIdResponse")
    @WebResult(name = "GetHasQuestionBookVersionViewsByCourseIdResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfBookVersionView getHasQuestionBookVersionViewsByCourseId(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetAllBasketQuestion", action = "http://tempuri.org/ITikuService/GetAllBasketQuestion")
    @Action(input = "http://tempuri.org/ITikuService/GetAllBasketQuestion", output = "http://tempuri.org/ITikuService/GetAllBasketQuestionResponse")
    @RequestWrapper(localName = "GetAllBasketQuestion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBasketQuestion")
    @ResponseWrapper(localName = "GetAllBasketQuestionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBasketQuestionResponse")
    @WebResult(name = "GetAllBasketQuestionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint getAllBasketQuestion(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetCourseQuestionCount", action = "http://tempuri.org/ITikuService/GetCourseQuestionCount")
    @Action(input = "http://tempuri.org/ITikuService/GetCourseQuestionCount", output = "http://tempuri.org/ITikuService/GetCourseQuestionCountResponse")
    @RequestWrapper(localName = "GetCourseQuestionCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseQuestionCount")
    @ResponseWrapper(localName = "GetCourseQuestionCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseQuestionCountResponse")
    @WebResult(name = "GetCourseQuestionCountResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.CourseBookVersionListView getCourseQuestionCount(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetExamUsageRuler", action = "http://tempuri.org/ITikuService/GetExamUsageRuler")
    @Action(input = "http://tempuri.org/ITikuService/GetExamUsageRuler", output = "http://tempuri.org/ITikuService/GetExamUsageRulerResponse")
    @RequestWrapper(localName = "GetExamUsageRuler", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamUsageRuler")
    @ResponseWrapper(localName = "GetExamUsageRulerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamUsageRulerResponse")
    @WebResult(name = "GetExamUsageRulerResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ExamUsageRuler getExamUsageRuler(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetExamUsageRulerRequest request
    );

    @WebMethod(operationName = "GetCourseAllChapterSections", action = "http://tempuri.org/ITikuService/GetCourseAllChapterSections")
    @Action(input = "http://tempuri.org/ITikuService/GetCourseAllChapterSections", output = "http://tempuri.org/ITikuService/GetCourseAllChapterSectionsResponse")
    @RequestWrapper(localName = "GetCourseAllChapterSections", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseAllChapterSections")
    @ResponseWrapper(localName = "GetCourseAllChapterSectionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseAllChapterSectionsResponse")
    @WebResult(name = "GetCourseAllChapterSectionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfintChapterSectionyHSjzk5H getCourseAllChapterSections(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetQuestionCategoryModels", action = "http://tempuri.org/ITikuService/GetQuestionCategoryModels")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionCategoryModels", output = "http://tempuri.org/ITikuService/GetQuestionCategoryModelsResponse")
    @RequestWrapper(localName = "GetQuestionCategoryModels", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoryModels")
    @ResponseWrapper(localName = "GetQuestionCategoryModelsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoryModelsResponse")
    @WebResult(name = "GetQuestionCategoryModelsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategoryModel getQuestionCategoryModels();

    @WebMethod(operationName = "GetCourseAllQuestionCount", action = "http://tempuri.org/ITikuService/GetCourseAllQuestionCount")
    @Action(input = "http://tempuri.org/ITikuService/GetCourseAllQuestionCount", output = "http://tempuri.org/ITikuService/GetCourseAllQuestionCountResponse")
    @RequestWrapper(localName = "GetCourseAllQuestionCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseAllQuestionCount")
    @ResponseWrapper(localName = "GetCourseAllQuestionCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseAllQuestionCountResponse")
    @WebResult(name = "GetCourseAllQuestionCountResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer getCourseAllQuestionCount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "RemoveQuestions", action = "http://tempuri.org/ITikuService/RemoveQuestions")
    @Action(input = "http://tempuri.org/ITikuService/RemoveQuestions", output = "http://tempuri.org/ITikuService/RemoveQuestionsResponse")
    @RequestWrapper(localName = "RemoveQuestions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveQuestions")
    @ResponseWrapper(localName = "RemoveQuestionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveQuestionsResponse")
    public void removeQuestions(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "questionCategoryId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionCategoryId
    );

    @WebMethod(operationName = "GetExamRuler", action = "http://tempuri.org/ITikuService/GetExamRuler")
    @Action(input = "http://tempuri.org/ITikuService/GetExamRuler", output = "http://tempuri.org/ITikuService/GetExamRulerResponse")
    @RequestWrapper(localName = "GetExamRuler", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamRuler")
    @ResponseWrapper(localName = "GetExamRulerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamRulerResponse")
    @WebResult(name = "GetExamRulerResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ExamRuler getExamRuler(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetChapterSectionKnowledgeMappingByCourseId", action = "http://tempuri.org/ITikuService/GetChapterSectionKnowledgeMappingByCourseId")
    @Action(input = "http://tempuri.org/ITikuService/GetChapterSectionKnowledgeMappingByCourseId", output = "http://tempuri.org/ITikuService/GetChapterSectionKnowledgeMappingByCourseIdResponse")
    @RequestWrapper(localName = "GetChapterSectionKnowledgeMappingByCourseId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSectionKnowledgeMappingByCourseId")
    @ResponseWrapper(localName = "GetChapterSectionKnowledgeMappingByCourseIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSectionKnowledgeMappingByCourseIdResponse")
    @WebResult(name = "GetChapterSectionKnowledgeMappingByCourseIdResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfChapterSectionKnowledgeMapping getChapterSectionKnowledgeMappingByCourseId(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetQuestionByIdForJava", action = "http://tempuri.org/ITikuService/GetQuestionByIdForJava")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionByIdForJava", output = "http://tempuri.org/ITikuService/GetQuestionByIdForJavaResponse")
    @RequestWrapper(localName = "GetQuestionByIdForJava", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionByIdForJava")
    @ResponseWrapper(localName = "GetQuestionByIdForJavaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionByIdForJavaResponse")
    @WebResult(name = "GetQuestionByIdForJavaResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.Question getQuestionByIdForJava(
        @WebParam(name = "questionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionId
    );

    @WebMethod(operationName = "GetFirstLevelChildrenKnowledgePointByQuestionSummary", action = "http://tempuri.org/ITikuService/GetFirstLevelChildrenKnowledgePointByQuestionSummary")
    @Action(input = "http://tempuri.org/ITikuService/GetFirstLevelChildrenKnowledgePointByQuestionSummary", output = "http://tempuri.org/ITikuService/GetFirstLevelChildrenKnowledgePointByQuestionSummaryResponse")
    @RequestWrapper(localName = "GetFirstLevelChildrenKnowledgePointByQuestionSummary", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFirstLevelChildrenKnowledgePointByQuestionSummary")
    @ResponseWrapper(localName = "GetFirstLevelChildrenKnowledgePointByQuestionSummaryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFirstLevelChildrenKnowledgePointByQuestionSummaryResponse")
    @WebResult(name = "GetFirstLevelChildrenKnowledgePointByQuestionSummaryResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfKnowledgePointView getFirstLevelChildrenKnowledgePointByQuestionSummary(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "parentKnowledgePointId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer parentKnowledgePointId,
        @WebParam(name = "maxLevel", targetNamespace = "http://tempuri.org/")
        java.lang.Integer maxLevel
    );

    @WebMethod(operationName = "GetAllQuestionCategories", action = "http://tempuri.org/ITikuService/GetAllQuestionCategories")
    @Action(input = "http://tempuri.org/ITikuService/GetAllQuestionCategories", output = "http://tempuri.org/ITikuService/GetAllQuestionCategoriesResponse")
    @RequestWrapper(localName = "GetAllQuestionCategories", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllQuestionCategories")
    @ResponseWrapper(localName = "GetAllQuestionCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllQuestionCategoriesResponse")
    @WebResult(name = "GetAllQuestionCategoriesResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory getAllQuestionCategories(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetAllQuestionCategoriesRequest request
    );

    @WebMethod(operationName = "GetQuestionCategoriesCheckOnline", action = "http://tempuri.org/ITikuService/GetQuestionCategoriesCheckOnline")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionCategoriesCheckOnline", output = "http://tempuri.org/ITikuService/GetQuestionCategoriesCheckOnlineResponse")
    @RequestWrapper(localName = "GetQuestionCategoriesCheckOnline", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoriesCheckOnline")
    @ResponseWrapper(localName = "GetQuestionCategoriesCheckOnlineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoriesCheckOnlineResponse")
    @WebResult(name = "GetQuestionCategoriesCheckOnlineResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory getQuestionCategoriesCheckOnline(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "supportOnline", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean supportOnline
    );

    @WebMethod(operationName = "SearchCllectionQuestions", action = "http://tempuri.org/ITikuService/SearchCllectionQuestions")
    @Action(input = "http://tempuri.org/ITikuService/SearchCllectionQuestions", output = "http://tempuri.org/ITikuService/SearchCllectionQuestionsResponse")
    @RequestWrapper(localName = "SearchCllectionQuestions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchCllectionQuestions")
    @ResponseWrapper(localName = "SearchCllectionQuestionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchCllectionQuestionsResponse")
    @WebResult(name = "SearchCllectionQuestionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView searchCllectionQuestions(
        @WebParam(name = "bookVersionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookVersionId,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        java.lang.String keyword,
        @WebParam(name = "onlineOnly", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean onlineOnly,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "pageNumber", targetNamespace = "http://tempuri.org/")
        java.lang.Integer pageNumber,
        @WebParam(name = "numberRecords", targetNamespace = "http://tempuri.org/")
        java.lang.Integer numberRecords
    );

    @WebMethod(operationName = "Empty", action = "http://tempuri.org/ITikuService/Empty")
    @Action(input = "http://tempuri.org/ITikuService/Empty", output = "http://tempuri.org/ITikuService/EmptyResponse")
    @RequestWrapper(localName = "Empty", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Empty")
    @ResponseWrapper(localName = "EmptyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmptyResponse")
    public void empty(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetBookVersions", action = "http://tempuri.org/ITikuService/GetBookVersions")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersions", output = "http://tempuri.org/ITikuService/GetBookVersionsResponse")
    @RequestWrapper(localName = "GetBookVersions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersions")
    @ResponseWrapper(localName = "GetBookVersionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionsResponse")
    @WebResult(name = "GetBookVersionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfBookVersion getBookVersions(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetBookVersionsRequest request
    );

    @WebMethod(operationName = "GetBookVersionId", action = "http://tempuri.org/ITikuService/GetBookVersionId")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersionId", output = "http://tempuri.org/ITikuService/GetBookVersionIdResponse")
    @RequestWrapper(localName = "GetBookVersionId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionId")
    @ResponseWrapper(localName = "GetBookVersionIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionIdResponse")
    @WebResult(name = "GetBookVersionIdResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer getBookVersionId(
        @WebParam(name = "courseMappingId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseMappingId
    );

    @WebMethod(operationName = "GetQuestionsByFilter", action = "http://tempuri.org/ITikuService/GetQuestionsByFilter")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionsByFilter", output = "http://tempuri.org/ITikuService/GetQuestionsByFilterResponse")
    @RequestWrapper(localName = "GetQuestionsByFilter", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsByFilter")
    @ResponseWrapper(localName = "GetQuestionsByFilterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsByFilterResponse")
    @WebResult(name = "GetQuestionsByFilterResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestion getQuestionsByFilter(
        @WebParam(name = "questionIds", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint questionIds,
        @WebParam(name = "filterUnavaliableQuestions", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean filterUnavaliableQuestions
    );

    @WebMethod(operationName = "GetOnlineQuestionsForKnowledgePoint", action = "http://tempuri.org/ITikuService/GetOnlineQuestionsForKnowledgePoint")
    @Action(input = "http://tempuri.org/ITikuService/GetOnlineQuestionsForKnowledgePoint", output = "http://tempuri.org/ITikuService/GetOnlineQuestionsForKnowledgePointResponse")
    @RequestWrapper(localName = "GetOnlineQuestionsForKnowledgePoint", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOnlineQuestionsForKnowledgePoint")
    @ResponseWrapper(localName = "GetOnlineQuestionsForKnowledgePointResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOnlineQuestionsForKnowledgePointResponse")
    @WebResult(name = "GetOnlineQuestionsForKnowledgePointResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.OnlineQuestionSimplifiedFormatKnowledgePointList getOnlineQuestionsForKnowledgePoint(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetOnlineQuestionsForKnowledgePointRequest request
    );

    @WebMethod(operationName = "GetBookVersionsByCourse", action = "http://tempuri.org/ITikuService/GetBookVersionsByCourse")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersionsByCourse", output = "http://tempuri.org/ITikuService/GetBookVersionsByCourseResponse")
    @RequestWrapper(localName = "GetBookVersionsByCourse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionsByCourse")
    @ResponseWrapper(localName = "GetBookVersionsByCourseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionsByCourseResponse")
    @WebResult(name = "GetBookVersionsByCourseResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfBookVersion getBookVersionsByCourse(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "isIncludeDeleted", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean isIncludeDeleted
    );

    @WebMethod(operationName = "GetCourseMapping", action = "http://tempuri.org/ITikuService/GetCourseMapping")
    @Action(input = "http://tempuri.org/ITikuService/GetCourseMapping", output = "http://tempuri.org/ITikuService/GetCourseMappingResponse")
    @RequestWrapper(localName = "GetCourseMapping", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseMapping")
    @ResponseWrapper(localName = "GetCourseMappingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseMappingResponse")
    @WebResult(name = "GetCourseMappingResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.CourseMapping getCourseMapping(
        @WebParam(name = "courseMappingId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseMappingId
    );

    @WebMethod(operationName = "GetClassRoomEvaluationDefaultSelected", action = "http://tempuri.org/ITikuService/GetClassRoomEvaluationDefaultSelected")
    @Action(input = "http://tempuri.org/ITikuService/GetClassRoomEvaluationDefaultSelected", output = "http://tempuri.org/ITikuService/GetClassRoomEvaluationDefaultSelectedResponse")
    @RequestWrapper(localName = "GetClassRoomEvaluationDefaultSelected", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClassRoomEvaluationDefaultSelected")
    @ResponseWrapper(localName = "GetClassRoomEvaluationDefaultSelectedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClassRoomEvaluationDefaultSelectedResponse")
    @WebResult(name = "GetClassRoomEvaluationDefaultSelectedResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ClassRoomEvaluationDefaultSelected getClassRoomEvaluationDefaultSelected(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetQuestionsForJava", action = "http://tempuri.org/ITikuService/GetQuestionsForJava")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionsForJava", output = "http://tempuri.org/ITikuService/GetQuestionsForJavaResponse")
    @RequestWrapper(localName = "GetQuestionsForJava", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsForJava")
    @ResponseWrapper(localName = "GetQuestionsForJavaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsForJavaResponse")
    @WebResult(name = "GetQuestionsForJavaResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestion getQuestionsForJava(
        @WebParam(name = "questionIds", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint questionIds
    );

    @WebMethod(operationName = "GetBookVersionChapterSections", action = "http://tempuri.org/ITikuService/GetBookVersionChapterSections")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersionChapterSections", output = "http://tempuri.org/ITikuService/GetBookVersionChapterSectionsResponse")
    @RequestWrapper(localName = "GetBookVersionChapterSections", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionChapterSections")
    @ResponseWrapper(localName = "GetBookVersionChapterSectionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionChapterSectionsResponse")
    @WebResult(name = "GetBookVersionChapterSectionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfintChapterSectionyHSjzk5H getBookVersionChapterSections(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetChapterSectionSimpleTreeByPage", action = "http://tempuri.org/ITikuService/GetChapterSectionSimpleTreeByPage")
    @Action(input = "http://tempuri.org/ITikuService/GetChapterSectionSimpleTreeByPage", output = "http://tempuri.org/ITikuService/GetChapterSectionSimpleTreeByPageResponse")
    @RequestWrapper(localName = "GetChapterSectionSimpleTreeByPage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSectionSimpleTreeByPage")
    @ResponseWrapper(localName = "GetChapterSectionSimpleTreeByPageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSectionSimpleTreeByPageResponse")
    @WebResult(name = "GetChapterSectionSimpleTreeByPageResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree getChapterSectionSimpleTreeByPage(
        @WebParam(name = "courseMappingId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseMappingId,
        @WebParam(name = "pageindex", targetNamespace = "http://tempuri.org/")
        java.lang.Integer pageindex,
        @WebParam(name = "pagesize", targetNamespace = "http://tempuri.org/")
        java.lang.Integer pagesize
    );

    @WebMethod(operationName = "GetExamSetQuestionDistribution", action = "http://tempuri.org/ITikuService/GetExamSetQuestionDistribution")
    @Action(input = "http://tempuri.org/ITikuService/GetExamSetQuestionDistribution", output = "http://tempuri.org/ITikuService/GetExamSetQuestionDistributionResponse")
    @RequestWrapper(localName = "GetExamSetQuestionDistribution", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamSetQuestionDistribution")
    @ResponseWrapper(localName = "GetExamSetQuestionDistributionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamSetQuestionDistributionResponse")
    @WebResult(name = "GetExamSetQuestionDistributionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree getExamSetQuestionDistribution(
        @WebParam(name = "examSetId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer examSetId,
        @WebParam(name = "bySection", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean bySection
    );

    @WebMethod(operationName = "AddQuestion", action = "http://tempuri.org/ITikuService/AddQuestion")
    @Action(input = "http://tempuri.org/ITikuService/AddQuestion", output = "http://tempuri.org/ITikuService/AddQuestionResponse")
    @RequestWrapper(localName = "AddQuestion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddQuestion")
    @ResponseWrapper(localName = "AddQuestionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddQuestionResponse")
    @WebResult(name = "AddQuestionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addQuestion(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "questionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionId,
        @WebParam(name = "bookversionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookversionId
    );

    @WebMethod(operationName = "GetBookVersionByUserId", action = "http://tempuri.org/ITikuService/GetBookVersionByUserId")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersionByUserId", output = "http://tempuri.org/ITikuService/GetBookVersionByUserIdResponse")
    @RequestWrapper(localName = "GetBookVersionByUserId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionByUserId")
    @ResponseWrapper(localName = "GetBookVersionByUserIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionByUserIdResponse")
    @WebResult(name = "GetBookVersionByUserIdResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.BookVersion getBookVersionByUserId(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetAllBookVersions", action = "http://tempuri.org/ITikuService/GetAllBookVersions")
    @Action(input = "http://tempuri.org/ITikuService/GetAllBookVersions", output = "http://tempuri.org/ITikuService/GetAllBookVersionsResponse")
    @RequestWrapper(localName = "GetAllBookVersions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBookVersions")
    @ResponseWrapper(localName = "GetAllBookVersionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBookVersionsResponse")
    @WebResult(name = "GetAllBookVersionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfBookVersion getAllBookVersions(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetBookVersionsRequest request
    );

    @WebMethod(operationName = "GetKnowledgePointSimpleTree", action = "http://tempuri.org/ITikuService/GetKnowledgePointSimpleTree")
    @Action(input = "http://tempuri.org/ITikuService/GetKnowledgePointSimpleTree", output = "http://tempuri.org/ITikuService/GetKnowledgePointSimpleTreeResponse")
    @RequestWrapper(localName = "GetKnowledgePointSimpleTree", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKnowledgePointSimpleTree")
    @ResponseWrapper(localName = "GetKnowledgePointSimpleTreeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKnowledgePointSimpleTreeResponse")
    @WebResult(name = "GetKnowledgePointSimpleTreeResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree getKnowledgePointSimpleTree(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetQuestionReportModel", action = "http://tempuri.org/ITikuService/GetQuestionReportModel")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionReportModel", output = "http://tempuri.org/ITikuService/GetQuestionReportModelResponse")
    @RequestWrapper(localName = "GetQuestionReportModel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionReportModel")
    @ResponseWrapper(localName = "GetQuestionReportModelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionReportModelResponse")
    @WebResult(name = "GetQuestionReportModelResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionReportModel getQuestionReportModel(
        @WebParam(name = "questionId", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint questionId
    );

    @WebMethod(operationName = "GetRootQuestionCategoriesCheckOnline", action = "http://tempuri.org/ITikuService/GetRootQuestionCategoriesCheckOnline")
    @Action(input = "http://tempuri.org/ITikuService/GetRootQuestionCategoriesCheckOnline", output = "http://tempuri.org/ITikuService/GetRootQuestionCategoriesCheckOnlineResponse")
    @RequestWrapper(localName = "GetRootQuestionCategoriesCheckOnline", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRootQuestionCategoriesCheckOnline")
    @ResponseWrapper(localName = "GetRootQuestionCategoriesCheckOnlineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRootQuestionCategoriesCheckOnlineResponse")
    @WebResult(name = "GetRootQuestionCategoriesCheckOnlineResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory getRootQuestionCategoriesCheckOnline(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionCategoriesCheckOnlineRequest request
    );

    @WebMethod(operationName = "AddMultipleQuestion", action = "http://tempuri.org/ITikuService/AddMultipleQuestion")
    @Action(input = "http://tempuri.org/ITikuService/AddMultipleQuestion", output = "http://tempuri.org/ITikuService/AddMultipleQuestionResponse")
    @RequestWrapper(localName = "AddMultipleQuestion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddMultipleQuestion")
    @ResponseWrapper(localName = "AddMultipleQuestionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddMultipleQuestionResponse")
    @WebResult(name = "AddMultipleQuestionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addMultipleQuestion(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "questionIds", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring questionIds,
        @WebParam(name = "bookversionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookversionId
    );

    @WebMethod(operationName = "GetQuestionsFromSections", action = "http://tempuri.org/ITikuService/GetQuestionsFromSections")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionsFromSections", output = "http://tempuri.org/ITikuService/GetQuestionsFromSectionsResponse")
    @RequestWrapper(localName = "GetQuestionsFromSections", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsFromSections")
    @ResponseWrapper(localName = "GetQuestionsFromSectionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsFromSectionsResponse")
    @WebResult(name = "GetQuestionsFromSectionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView getQuestionsFromSections(
        @WebParam(name = "courseMappingId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseMappingId,
        @WebParam(name = "onlineOnly", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean onlineOnly,
        @WebParam(name = "questionLevel", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionLevel,
        @WebParam(name = "questionCategory", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionCategory,
        @WebParam(name = "pageNumber", targetNamespace = "http://tempuri.org/")
        java.lang.Integer pageNumber,
        @WebParam(name = "numberRecords", targetNamespace = "http://tempuri.org/")
        java.lang.Integer numberRecords,
        @WebParam(name = "sectionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer sectionId
    );

    @WebMethod(operationName = "GetChapterSection", action = "http://tempuri.org/ITikuService/GetChapterSection")
    @Action(input = "http://tempuri.org/ITikuService/GetChapterSection", output = "http://tempuri.org/ITikuService/GetChapterSectionResponse")
    @RequestWrapper(localName = "GetChapterSection", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSection")
    @ResponseWrapper(localName = "GetChapterSectionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSectionResponse")
    @WebResult(name = "GetChapterSectionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ChapterSectionView getChapterSection(
        @WebParam(name = "sectionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer sectionId,
        @WebParam(name = "courseMappingId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseMappingId
    );

    @WebMethod(operationName = "GetCourseMappingsByCourseId", action = "http://tempuri.org/ITikuService/GetCourseMappingsByCourseId")
    @Action(input = "http://tempuri.org/ITikuService/GetCourseMappingsByCourseId", output = "http://tempuri.org/ITikuService/GetCourseMappingsByCourseIdResponse")
    @RequestWrapper(localName = "GetCourseMappingsByCourseId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseMappingsByCourseId")
    @ResponseWrapper(localName = "GetCourseMappingsByCourseIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCourseMappingsByCourseIdResponse")
    @WebResult(name = "GetCourseMappingsByCourseIdResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfCourseMapping getCourseMappingsByCourseId(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetExamUsageRulerView", action = "http://tempuri.org/ITikuService/GetExamUsageRulerView")
    @Action(input = "http://tempuri.org/ITikuService/GetExamUsageRulerView", output = "http://tempuri.org/ITikuService/GetExamUsageRulerViewResponse")
    @RequestWrapper(localName = "GetExamUsageRulerView", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamUsageRulerView")
    @ResponseWrapper(localName = "GetExamUsageRulerViewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExamUsageRulerViewResponse")
    @WebResult(name = "GetExamUsageRulerViewResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ExamUsageRulerView getExamUsageRulerView(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetExamUsageRulerViewRequest request
    );

    @WebMethod(operationName = "GetQuestionDisplayType", action = "http://tempuri.org/ITikuService/GetQuestionDisplayType")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionDisplayType", output = "http://tempuri.org/ITikuService/GetQuestionDisplayTypeResponse")
    @RequestWrapper(localName = "GetQuestionDisplayType", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionDisplayType")
    @ResponseWrapper(localName = "GetQuestionDisplayTypeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionDisplayTypeResponse")
    @WebResult(name = "GetQuestionDisplayTypeResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.QuestionDisplayType getQuestionDisplayType(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "CheckSCPQuestion", action = "http://tempuri.org/ITikuService/CheckSCPQuestion")
    @Action(input = "http://tempuri.org/ITikuService/CheckSCPQuestion", output = "http://tempuri.org/ITikuService/CheckSCPQuestionResponse")
    @RequestWrapper(localName = "CheckSCPQuestion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckSCPQuestion")
    @ResponseWrapper(localName = "CheckSCPQuestionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckSCPQuestionResponse")
    @WebResult(name = "CheckSCPQuestionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.CheckSCPQuestionView checkSCPQuestion(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.SCPQuestionRequest request
    );

    @WebMethod(operationName = "GetSCPQuestionDetails", action = "http://tempuri.org/ITikuService/GetSCPQuestionDetails")
    @Action(input = "http://tempuri.org/ITikuService/GetSCPQuestionDetails", output = "http://tempuri.org/ITikuService/GetSCPQuestionDetailsResponse")
    @RequestWrapper(localName = "GetSCPQuestionDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSCPQuestionDetails")
    @ResponseWrapper(localName = "GetSCPQuestionDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSCPQuestionDetailsResponse")
    @WebResult(name = "GetSCPQuestionDetailsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.SCPQuestionDetailView getSCPQuestionDetails(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.SCPQuestionRequest request
    );

    @WebMethod(operationName = "GetPreviewConfigSession", action = "http://tempuri.org/ITikuService/GetPreviewConfigSession")
    @Action(input = "http://tempuri.org/ITikuService/GetPreviewConfigSession", output = "http://tempuri.org/ITikuService/GetPreviewConfigSessionResponse")
    @RequestWrapper(localName = "GetPreviewConfigSession", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPreviewConfigSession")
    @ResponseWrapper(localName = "GetPreviewConfigSessionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPreviewConfigSessionResponse")
    @WebResult(name = "GetPreviewConfigSessionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getPreviewConfigSession(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "online", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean online
    );

    @WebMethod(operationName = "GetQuestions", action = "http://tempuri.org/ITikuService/GetQuestions")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestions", output = "http://tempuri.org/ITikuService/GetQuestionsResponse")
    @RequestWrapper(localName = "GetQuestions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestions")
    @ResponseWrapper(localName = "GetQuestionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsResponse")
    @WebResult(name = "GetQuestionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestion getQuestions(
        @WebParam(name = "questionIds", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint questionIds
    );

    @WebMethod(operationName = "GenerateOneClickTestPaperQuestions", action = "http://tempuri.org/ITikuService/GenerateOneClickTestPaperQuestions")
    @Action(input = "http://tempuri.org/ITikuService/GenerateOneClickTestPaperQuestions", output = "http://tempuri.org/ITikuService/GenerateOneClickTestPaperQuestionsResponse")
    @RequestWrapper(localName = "GenerateOneClickTestPaperQuestions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateOneClickTestPaperQuestions")
    @ResponseWrapper(localName = "GenerateOneClickTestPaperQuestionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateOneClickTestPaperQuestionsResponse")
    @WebResult(name = "GenerateOneClickTestPaperQuestionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.OneClickTestPaperResultView generateOneClickTestPaperQuestions(
        @WebParam(name = "oneClickTestPaperRequest", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.OneClickTestPaperRequest oneClickTestPaperRequest
    );

    @WebMethod(operationName = "GetQuestionLabels", action = "http://tempuri.org/ITikuService/GetQuestionLabels")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionLabels", output = "http://tempuri.org/ITikuService/GetQuestionLabelsResponse")
    @RequestWrapper(localName = "GetQuestionLabels", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionLabels")
    @ResponseWrapper(localName = "GetQuestionLabelsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionLabelsResponse")
    @WebResult(name = "GetQuestionLabelsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionLabel getQuestionLabels(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetAllCourseMappings", action = "http://tempuri.org/ITikuService/GetAllCourseMappings")
    @Action(input = "http://tempuri.org/ITikuService/GetAllCourseMappings", output = "http://tempuri.org/ITikuService/GetAllCourseMappingsResponse")
    @RequestWrapper(localName = "GetAllCourseMappings", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllCourseMappings")
    @ResponseWrapper(localName = "GetAllCourseMappingsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllCourseMappingsResponse")
    @WebResult(name = "GetAllCourseMappingsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfCourseMapping getAllCourseMappings();

    @WebMethod(operationName = "GetFirstLevelChildrenKnowledgePointByQuestionSummary_V2", action = "http://tempuri.org/ITikuService/GetFirstLevelChildrenKnowledgePointByQuestionSummary_V2")
    @Action(input = "http://tempuri.org/ITikuService/GetFirstLevelChildrenKnowledgePointByQuestionSummary_V2", output = "http://tempuri.org/ITikuService/GetFirstLevelChildrenKnowledgePointByQuestionSummary_V2Response")
    @RequestWrapper(localName = "GetFirstLevelChildrenKnowledgePointByQuestionSummary_V2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFirstLevelChildrenKnowledgePointByQuestionSummaryV2")
    @ResponseWrapper(localName = "GetFirstLevelChildrenKnowledgePointByQuestionSummary_V2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFirstLevelChildrenKnowledgePointByQuestionSummaryV2Response")
    @WebResult(name = "GetFirstLevelChildrenKnowledgePointByQuestionSummary_V2Result", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfKnowledgePointView getFirstLevelChildrenKnowledgePointByQuestionSummaryV2(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.KnowledgePointQuestionRequest request
    );

    @WebMethod(operationName = "GetQuestionsFromKnowledgePoints", action = "http://tempuri.org/ITikuService/GetQuestionsFromKnowledgePoints")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionsFromKnowledgePoints", output = "http://tempuri.org/ITikuService/GetQuestionsFromKnowledgePointsResponse")
    @RequestWrapper(localName = "GetQuestionsFromKnowledgePoints", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsFromKnowledgePoints")
    @ResponseWrapper(localName = "GetQuestionsFromKnowledgePointsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionsFromKnowledgePointsResponse")
    @WebResult(name = "GetQuestionsFromKnowledgePointsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView getQuestionsFromKnowledgePoints(
        @WebParam(name = "bookVersionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bookVersionId,
        @WebParam(name = "onlineOnly", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean onlineOnly,
        @WebParam(name = "questionLevel", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionLevel,
        @WebParam(name = "questionCategory", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionCategory,
        @WebParam(name = "pageNumber", targetNamespace = "http://tempuri.org/")
        java.lang.Integer pageNumber,
        @WebParam(name = "numberRecords", targetNamespace = "http://tempuri.org/")
        java.lang.Integer numberRecords,
        @WebParam(name = "knowledgePointId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer knowledgePointId
    );

    @WebMethod(operationName = "GetCoursePreKnowledgePoints", action = "http://tempuri.org/ITikuService/GetCoursePreKnowledgePoints")
    @Action(input = "http://tempuri.org/ITikuService/GetCoursePreKnowledgePoints", output = "http://tempuri.org/ITikuService/GetCoursePreKnowledgePointsResponse")
    @RequestWrapper(localName = "GetCoursePreKnowledgePoints", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCoursePreKnowledgePoints")
    @ResponseWrapper(localName = "GetCoursePreKnowledgePointsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCoursePreKnowledgePointsResponse")
    @WebResult(name = "GetCoursePreKnowledgePointsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.PreKnowledgePointList getCoursePreKnowledgePoints(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetParentChapterSections", action = "http://tempuri.org/ITikuService/GetParentChapterSections")
    @Action(input = "http://tempuri.org/ITikuService/GetParentChapterSections", output = "http://tempuri.org/ITikuService/GetParentChapterSectionsResponse")
    @RequestWrapper(localName = "GetParentChapterSections", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetParentChapterSections")
    @ResponseWrapper(localName = "GetParentChapterSectionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetParentChapterSectionsResponse")
    @WebResult(name = "GetParentChapterSectionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfChapterSection getParentChapterSections(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetQuestionCategories", action = "http://tempuri.org/ITikuService/GetQuestionCategories")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionCategories", output = "http://tempuri.org/ITikuService/GetQuestionCategoriesResponse")
    @RequestWrapper(localName = "GetQuestionCategories", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategories")
    @ResponseWrapper(localName = "GetQuestionCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoriesResponse")
    @WebResult(name = "GetQuestionCategoriesResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory getQuestionCategories(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "RemovePreviewConfigSession", action = "http://tempuri.org/ITikuService/RemovePreviewConfigSession")
    @Action(input = "http://tempuri.org/ITikuService/RemovePreviewConfigSession", output = "http://tempuri.org/ITikuService/RemovePreviewConfigSessionResponse")
    @RequestWrapper(localName = "RemovePreviewConfigSession", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemovePreviewConfigSession")
    @ResponseWrapper(localName = "RemovePreviewConfigSessionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemovePreviewConfigSessionResponse")
    public void removePreviewConfigSession(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "online", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean online
    );

    @WebMethod(operationName = "GetChapterSectionSimpleTree", action = "http://tempuri.org/ITikuService/GetChapterSectionSimpleTree")
    @Action(input = "http://tempuri.org/ITikuService/GetChapterSectionSimpleTree", output = "http://tempuri.org/ITikuService/GetChapterSectionSimpleTreeResponse")
    @RequestWrapper(localName = "GetChapterSectionSimpleTree", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSectionSimpleTree")
    @ResponseWrapper(localName = "GetChapterSectionSimpleTreeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSectionSimpleTreeResponse")
    @WebResult(name = "GetChapterSectionSimpleTreeResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree getChapterSectionSimpleTree(
        @WebParam(name = "courseMappingId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseMappingId
    );

    @WebMethod(operationName = "GetChapterSections", action = "http://tempuri.org/ITikuService/GetChapterSections")
    @Action(input = "http://tempuri.org/ITikuService/GetChapterSections", output = "http://tempuri.org/ITikuService/GetChapterSectionsResponse")
    @RequestWrapper(localName = "GetChapterSections", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSections")
    @ResponseWrapper(localName = "GetChapterSectionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChapterSectionsResponse")
    @WebResult(name = "GetChapterSectionsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ChapterSectionList getChapterSections(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetAllExamUsageRulers", action = "http://tempuri.org/ITikuService/GetAllExamUsageRulers")
    @Action(input = "http://tempuri.org/ITikuService/GetAllExamUsageRulers", output = "http://tempuri.org/ITikuService/GetAllExamUsageRulersResponse")
    @RequestWrapper(localName = "GetAllExamUsageRulers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllExamUsageRulers")
    @ResponseWrapper(localName = "GetAllExamUsageRulersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllExamUsageRulersResponse")
    @WebResult(name = "GetAllExamUsageRulersResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfExamUsageRuler getAllExamUsageRulers();

    @WebMethod(operationName = "GetSimilarQuestionList", action = "http://tempuri.org/ITikuService/GetSimilarQuestionList")
    @Action(input = "http://tempuri.org/ITikuService/GetSimilarQuestionList", output = "http://tempuri.org/ITikuService/GetSimilarQuestionListResponse")
    @RequestWrapper(localName = "GetSimilarQuestionList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSimilarQuestionList")
    @ResponseWrapper(localName = "GetSimilarQuestionListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSimilarQuestionListResponse")
    @WebResult(name = "GetSimilarQuestionListResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.SimilarQuestionList getSimilarQuestionList(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest request
    );

    @WebMethod(operationName = "GetBookVersion", action = "http://tempuri.org/ITikuService/GetBookVersion")
    @Action(input = "http://tempuri.org/ITikuService/GetBookVersion", output = "http://tempuri.org/ITikuService/GetBookVersionResponse")
    @RequestWrapper(localName = "GetBookVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersion")
    @ResponseWrapper(localName = "GetBookVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookVersionResponse")
    @WebResult(name = "GetBookVersionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfBookVersion getBookVersion(
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetQuestionStatistics", action = "http://tempuri.org/ITikuService/GetQuestionStatistics")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionStatistics", output = "http://tempuri.org/ITikuService/GetQuestionStatisticsResponse")
    @RequestWrapper(localName = "GetQuestionStatistics", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionStatistics")
    @ResponseWrapper(localName = "GetQuestionStatisticsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionStatisticsResponse")
    @WebResult(name = "GetQuestionStatisticsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.QuestionStatistics getQuestionStatistics(
        @WebParam(name = "questionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer questionId
    );

    @WebMethod(operationName = "GetZujuanBasketStatistics", action = "http://tempuri.org/ITikuService/GetZujuanBasketStatistics")
    @Action(input = "http://tempuri.org/ITikuService/GetZujuanBasketStatistics", output = "http://tempuri.org/ITikuService/GetZujuanBasketStatisticsResponse")
    @RequestWrapper(localName = "GetZujuanBasketStatistics", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetZujuanBasketStatistics")
    @ResponseWrapper(localName = "GetZujuanBasketStatisticsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetZujuanBasketStatisticsResponse")
    @WebResult(name = "GetZujuanBasketStatisticsResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_exam.ArrayOfZujuanBasketQuestionCategoryStatisticsView getZujuanBasketStatistics(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        java.lang.String sessionId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId
    );

    @WebMethod(operationName = "GetQuestionStatisticsList", action = "http://tempuri.org/ITikuService/GetQuestionStatisticsList")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionStatisticsList", output = "http://tempuri.org/ITikuService/GetQuestionStatisticsListResponse")
    @RequestWrapper(localName = "GetQuestionStatisticsList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionStatisticsList")
    @ResponseWrapper(localName = "GetQuestionStatisticsListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionStatisticsListResponse")
    @WebResult(name = "GetQuestionStatisticsListResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionStatistics getQuestionStatisticsList(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionStatisticsListRequest request
    );

    @WebMethod(operationName = "GetHasQuestionBookVersion", action = "http://tempuri.org/ITikuService/GetHasQuestionBookVersion")
    @Action(input = "http://tempuri.org/ITikuService/GetHasQuestionBookVersion", output = "http://tempuri.org/ITikuService/GetHasQuestionBookVersionResponse")
    @RequestWrapper(localName = "GetHasQuestionBookVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHasQuestionBookVersion")
    @ResponseWrapper(localName = "GetHasQuestionBookVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHasQuestionBookVersionResponse")
    @WebResult(name = "GetHasQuestionBookVersionResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfBookVersionView getHasQuestionBookVersion(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer userId,
        @WebParam(name = "courseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer courseId,
        @WebParam(name = "includeSpecifyBookVersion", targetNamespace = "http://tempuri.org/")
        java.lang.String includeSpecifyBookVersion
    );

    @WebMethod(operationName = "GetGetQuestionDisplayTypes", action = "http://tempuri.org/ITikuService/GetGetQuestionDisplayTypes")
    @Action(input = "http://tempuri.org/ITikuService/GetGetQuestionDisplayTypes", output = "http://tempuri.org/ITikuService/GetGetQuestionDisplayTypesResponse")
    @RequestWrapper(localName = "GetGetQuestionDisplayTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGetQuestionDisplayTypes")
    @ResponseWrapper(localName = "GetGetQuestionDisplayTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGetQuestionDisplayTypesResponse")
    @WebResult(name = "GetGetQuestionDisplayTypesResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionDisplayType getGetQuestionDisplayTypes();

    @WebMethod(operationName = "GetQuestionCategoriesCheckOnlineNew", action = "http://tempuri.org/ITikuService/GetQuestionCategoriesCheckOnlineNew")
    @Action(input = "http://tempuri.org/ITikuService/GetQuestionCategoriesCheckOnlineNew", output = "http://tempuri.org/ITikuService/GetQuestionCategoriesCheckOnlineNewResponse")
    @RequestWrapper(localName = "GetQuestionCategoriesCheckOnlineNew", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoriesCheckOnlineNew")
    @ResponseWrapper(localName = "GetQuestionCategoriesCheckOnlineNewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQuestionCategoriesCheckOnlineNewResponse")
    @WebResult(name = "GetQuestionCategoriesCheckOnlineNewResult", targetNamespace = "http://tempuri.org/")
    public wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory getQuestionCategoriesCheckOnlineNew(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionCategoriesCheckOnlineRequest request
    );
}
