
package wcf.tikuservice.org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-19T19:32:58.483+08:00
 * Generated source version: 3.2.4
 *
 */
public final class ITikuService_BasicHttpBindingITikuService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "TikuService");

    private ITikuService_BasicHttpBindingITikuService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TikuService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TikuService ss = new TikuService(wsdlURL, SERVICE_NAME);
        ITikuService port = ss.getBasicHttpBindingITikuService();

        {
        System.out.println("Invoking getExamSetQuestionSection...");
        java.lang.String _getExamSetQuestionSection_sessionId = "";
        java.lang.Integer _getExamSetQuestionSection_bookversionId = null;
        java.lang.Boolean _getExamSetQuestionSection_online = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree _getExamSetQuestionSection__return = port.getExamSetQuestionSection(_getExamSetQuestionSection_sessionId, _getExamSetQuestionSection_bookversionId, _getExamSetQuestionSection_online);
        System.out.println("getExamSetQuestionSection.result=" + _getExamSetQuestionSection__return);


        }
        {
        System.out.println("Invoking getKnowledgePointQuestionCount...");
        java.lang.Integer _getKnowledgePointQuestionCount_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfKnowledgePointQuestionCount _getKnowledgePointQuestionCount__return = port.getKnowledgePointQuestionCount(_getKnowledgePointQuestionCount_courseId);
        System.out.println("getKnowledgePointQuestionCount.result=" + _getKnowledgePointQuestionCount__return);


        }
        {
        System.out.println("Invoking getQuestionFaultTypes...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionFaultType _getQuestionFaultTypes__return = port.getQuestionFaultTypes();
        System.out.println("getQuestionFaultTypes.result=" + _getQuestionFaultTypes__return);


        }
        {
        System.out.println("Invoking getKnowledgePoints...");
        java.lang.Integer _getKnowledgePoints_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.KnowledgePointList _getKnowledgePoints__return = port.getKnowledgePoints(_getKnowledgePoints_courseId);
        System.out.println("getKnowledgePoints.result=" + _getKnowledgePoints__return);


        }
        {
        System.out.println("Invoking setPreviewConfigSession...");
        java.lang.String _setPreviewConfigSession_sessionId = "";
        java.lang.String _setPreviewConfigSession_examConfig = "";
        java.lang.Boolean _setPreviewConfigSession_online = null;
        port.setPreviewConfigSession(_setPreviewConfigSession_sessionId, _setPreviewConfigSession_examConfig, _setPreviewConfigSession_online);


        }
        {
        System.out.println("Invoking removeQuestion...");
        java.lang.String _removeQuestion_sessionId = "";
        java.lang.Integer _removeQuestion_userId = null;
        java.lang.Integer _removeQuestion_courseId = null;
        java.lang.Integer _removeQuestion_questionId = null;
        port.removeQuestion(_removeQuestion_sessionId, _removeQuestion_userId, _removeQuestion_courseId, _removeQuestion_questionId);


        }
        {
        System.out.println("Invoking getAllPublishers...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfPublisher _getAllPublishers__return = port.getAllPublishers();
        System.out.println("getAllPublishers.result=" + _getAllPublishers__return);


        }
        {
        System.out.println("Invoking getQuestionById...");
        java.lang.Integer _getQuestionById_questionId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.Question _getQuestionById__return = port.getQuestionById(_getQuestionById_questionId);
        System.out.println("getQuestionById.result=" + _getQuestionById__return);


        }
        {
        System.out.println("Invoking getAllCollectionQuestion...");
        java.lang.Integer _getAllCollectionQuestion_bookVersionId = null;
        java.lang.Integer _getAllCollectionQuestion_userId = null;
        java.lang.Integer _getAllCollectionQuestion_pageNumber = null;
        java.lang.Integer _getAllCollectionQuestion_numberRecords = null;
        java.lang.Integer _getAllCollectionQuestion_courseId = null;
        java.lang.Boolean _getAllCollectionQuestion_online = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView _getAllCollectionQuestion__return = port.getAllCollectionQuestion(_getAllCollectionQuestion_bookVersionId, _getAllCollectionQuestion_userId, _getAllCollectionQuestion_pageNumber, _getAllCollectionQuestion_numberRecords, _getAllCollectionQuestion_courseId, _getAllCollectionQuestion_online);
        System.out.println("getAllCollectionQuestion.result=" + _getAllCollectionQuestion__return);


        }
        {
        System.out.println("Invoking getCourseMappingIdBySectionId...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetCourseMappingIdBySectionIdRequest _getCourseMappingIdBySectionId_request = null;
        java.lang.Integer _getCourseMappingIdBySectionId__return = port.getCourseMappingIdBySectionId(_getCourseMappingIdBySectionId_request);
        System.out.println("getCourseMappingIdBySectionId.result=" + _getCourseMappingIdBySectionId__return);


        }
        {
        System.out.println("Invoking getChapterList...");
        java.lang.Integer _getChapterList_courseMappingId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfChapterSectionView _getChapterList__return = port.getChapterList(_getChapterList_courseMappingId);
        System.out.println("getChapterList.result=" + _getChapterList__return);


        }
        {
        System.out.println("Invoking addQuestionOnClick...");
        java.lang.String _addQuestionOnClick_sessionId = "";
        java.lang.Integer _addQuestionOnClick_userId = null;
        java.lang.Integer _addQuestionOnClick_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionSimplifiedFormat _addQuestionOnClick_question = null;
        java.lang.Integer _addQuestionOnClick_bookversionId = null;
        port.addQuestionOnClick(_addQuestionOnClick_sessionId, _addQuestionOnClick_userId, _addQuestionOnClick_courseId, _addQuestionOnClick_question, _addQuestionOnClick_bookversionId);


        }
        {
        System.out.println("Invoking generateAutoZujuanQuestions...");
        java.lang.Integer _generateAutoZujuanQuestions_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_exam.AutoZujuanCreationRequest _generateAutoZujuanQuestions_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListCategorieCountView _generateAutoZujuanQuestions__return = port.generateAutoZujuanQuestions(_generateAutoZujuanQuestions_courseId, _generateAutoZujuanQuestions_request);
        System.out.println("generateAutoZujuanQuestions.result=" + _generateAutoZujuanQuestions__return);


        }
        {
        System.out.println("Invoking getCourseMappings...");
        java.lang.Integer _getCourseMappings_bookVersionId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfCourseMapping _getCourseMappings__return = port.getCourseMappings(_getCourseMappings_bookVersionId);
        System.out.println("getCourseMappings.result=" + _getCourseMappings__return);


        }
        {
        System.out.println("Invoking getSchoolBookVersion...");
        java.lang.Integer _getSchoolBookVersion_schoolId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfSchoolBookVersion _getSchoolBookVersion__return = port.getSchoolBookVersion(_getSchoolBookVersion_schoolId);
        System.out.println("getSchoolBookVersion.result=" + _getSchoolBookVersion__return);


        }
        {
        System.out.println("Invoking getBookVersionQuestionCount...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getBookVersionQuestionCount_request = null;
        java.lang.Integer _getBookVersionQuestionCount__return = port.getBookVersionQuestionCount(_getBookVersionQuestionCount_request);
        System.out.println("getBookVersionQuestionCount.result=" + _getBookVersionQuestionCount__return);


        }
        {
        System.out.println("Invoking searchQuestions...");
        java.lang.Integer _searchQuestions_bookVersionId = null;
        java.lang.String _searchQuestions_keyword = "";
        java.lang.Integer _searchQuestions_questionLevel = null;
        java.lang.Integer _searchQuestions_questionCategoryId = null;
        java.lang.Boolean _searchQuestions_onlineOnly = null;
        java.lang.Integer _searchQuestions_pageNumber = null;
        java.lang.Integer _searchQuestions_numberRecords = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView _searchQuestions__return = port.searchQuestions(_searchQuestions_bookVersionId, _searchQuestions_keyword, _searchQuestions_questionLevel, _searchQuestions_questionCategoryId, _searchQuestions_onlineOnly, _searchQuestions_pageNumber, _searchQuestions_numberRecords);
        System.out.println("searchQuestions.result=" + _searchQuestions__return);


        }
        {
        System.out.println("Invoking getQuestionSectionDistribution...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionSectionDistributionRequest _getQuestionSectionDistribution_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfQuestionSectionDistributionView _getQuestionSectionDistribution__return = port.getQuestionSectionDistribution(_getQuestionSectionDistribution_request);
        System.out.println("getQuestionSectionDistribution.result=" + _getQuestionSectionDistribution__return);


        }
        {
        System.out.println("Invoking getOnlineQuestions...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetOnlineQuestionsRequest _getOnlineQuestions_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.OnlineQuestionSimplifiedFormatSectionList _getOnlineQuestions__return = port.getOnlineQuestions(_getOnlineQuestions_request);
        System.out.println("getOnlineQuestions.result=" + _getOnlineQuestions__return);


        }
        {
        System.out.println("Invoking getBookVersionByCourse...");
        java.lang.Integer _getBookVersionByCourse_userId = null;
        java.lang.Integer _getBookVersionByCourse_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.BookVersion _getBookVersionByCourse__return = port.getBookVersionByCourse(_getBookVersionByCourse_userId, _getBookVersionByCourse_courseId);
        System.out.println("getBookVersionByCourse.result=" + _getBookVersionByCourse__return);


        }
        {
        System.out.println("Invoking getQuestionsFromCourseMappingAll...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionsFromCourseMappingAllRequest _getQuestionsFromCourseMappingAll_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionSimplifiedFormat _getQuestionsFromCourseMappingAll__return = port.getQuestionsFromCourseMappingAll(_getQuestionsFromCourseMappingAll_request);
        System.out.println("getQuestionsFromCourseMappingAll.result=" + _getQuestionsFromCourseMappingAll__return);


        }
        {
        System.out.println("Invoking getQuestionKnowledgePointDistribution...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionKnowledgePointDistributionRequest _getQuestionKnowledgePointDistribution_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfQuestionKnowledgePointDistributionView _getQuestionKnowledgePointDistribution__return = port.getQuestionKnowledgePointDistribution(_getQuestionKnowledgePointDistribution_request);
        System.out.println("getQuestionKnowledgePointDistribution.result=" + _getQuestionKnowledgePointDistribution__return);


        }
        {
        System.out.println("Invoking getQuestionsFromKnowledgePointsAll...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionsFromKnowledgePointsAllRequest _getQuestionsFromKnowledgePointsAll_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionSimplifiedFormatCache _getQuestionsFromKnowledgePointsAll__return = port.getQuestionsFromKnowledgePointsAll(_getQuestionsFromKnowledgePointsAll_request);
        System.out.println("getQuestionsFromKnowledgePointsAll.result=" + _getQuestionsFromKnowledgePointsAll__return);


        }
        {
        System.out.println("Invoking getBookVersionInfo...");
        java.lang.Integer _getBookVersionInfo_bookVersionId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.BookVersion _getBookVersionInfo__return = port.getBookVersionInfo(_getBookVersionInfo_bookVersionId);
        System.out.println("getBookVersionInfo.result=" + _getBookVersionInfo__return);


        }
        {
        System.out.println("Invoking getQuestionCategoryById...");
        java.lang.Integer _getQuestionCategoryById_categoryId = null;
        java.lang.Integer _getQuestionCategoryById_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.QuestionCategory _getQuestionCategoryById__return = port.getQuestionCategoryById(_getQuestionCategoryById_categoryId, _getQuestionCategoryById_courseId);
        System.out.println("getQuestionCategoryById.result=" + _getQuestionCategoryById__return);


        }
        {
        System.out.println("Invoking getHasQuestionBookVersionViewsByCourseId...");
        java.lang.Integer _getHasQuestionBookVersionViewsByCourseId_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfBookVersionView _getHasQuestionBookVersionViewsByCourseId__return = port.getHasQuestionBookVersionViewsByCourseId(_getHasQuestionBookVersionViewsByCourseId_courseId);
        System.out.println("getHasQuestionBookVersionViewsByCourseId.result=" + _getHasQuestionBookVersionViewsByCourseId__return);


        }
        {
        System.out.println("Invoking getAllBasketQuestion...");
        java.lang.String _getAllBasketQuestion_sessionId = "";
        java.lang.Integer _getAllBasketQuestion_userId = null;
        java.lang.Integer _getAllBasketQuestion_courseId = null;
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint _getAllBasketQuestion__return = port.getAllBasketQuestion(_getAllBasketQuestion_sessionId, _getAllBasketQuestion_userId, _getAllBasketQuestion_courseId);
        System.out.println("getAllBasketQuestion.result=" + _getAllBasketQuestion__return);


        }
        {
        System.out.println("Invoking getCourseQuestionCount...");
        java.lang.Integer _getCourseQuestionCount_userId = null;
        java.lang.Integer _getCourseQuestionCount_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.CourseBookVersionListView _getCourseQuestionCount__return = port.getCourseQuestionCount(_getCourseQuestionCount_userId, _getCourseQuestionCount_courseId);
        System.out.println("getCourseQuestionCount.result=" + _getCourseQuestionCount__return);


        }
        {
        System.out.println("Invoking getExamUsageRuler...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetExamUsageRulerRequest _getExamUsageRuler_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ExamUsageRuler _getExamUsageRuler__return = port.getExamUsageRuler(_getExamUsageRuler_request);
        System.out.println("getExamUsageRuler.result=" + _getExamUsageRuler__return);


        }
        {
        System.out.println("Invoking getCourseAllChapterSections...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getCourseAllChapterSections_request = null;
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfintChapterSectionyHSjzk5H _getCourseAllChapterSections__return = port.getCourseAllChapterSections(_getCourseAllChapterSections_request);
        System.out.println("getCourseAllChapterSections.result=" + _getCourseAllChapterSections__return);


        }
        {
        System.out.println("Invoking getQuestionCategoryModels...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategoryModel _getQuestionCategoryModels__return = port.getQuestionCategoryModels();
        System.out.println("getQuestionCategoryModels.result=" + _getQuestionCategoryModels__return);


        }
        {
        System.out.println("Invoking getCourseAllQuestionCount...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getCourseAllQuestionCount_request = null;
        java.lang.Integer _getCourseAllQuestionCount__return = port.getCourseAllQuestionCount(_getCourseAllQuestionCount_request);
        System.out.println("getCourseAllQuestionCount.result=" + _getCourseAllQuestionCount__return);


        }
        {
        System.out.println("Invoking removeQuestions...");
        java.lang.String _removeQuestions_sessionId = "";
        java.lang.Integer _removeQuestions_userId = null;
        java.lang.Integer _removeQuestions_courseId = null;
        java.lang.Integer _removeQuestions_questionCategoryId = null;
        port.removeQuestions(_removeQuestions_sessionId, _removeQuestions_userId, _removeQuestions_courseId, _removeQuestions_questionCategoryId);


        }
        {
        System.out.println("Invoking getExamRuler...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getExamRuler_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ExamRuler _getExamRuler__return = port.getExamRuler(_getExamRuler_request);
        System.out.println("getExamRuler.result=" + _getExamRuler__return);


        }
        {
        System.out.println("Invoking getChapterSectionKnowledgeMappingByCourseId...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getChapterSectionKnowledgeMappingByCourseId_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfChapterSectionKnowledgeMapping _getChapterSectionKnowledgeMappingByCourseId__return = port.getChapterSectionKnowledgeMappingByCourseId(_getChapterSectionKnowledgeMappingByCourseId_request);
        System.out.println("getChapterSectionKnowledgeMappingByCourseId.result=" + _getChapterSectionKnowledgeMappingByCourseId__return);


        }
        {
        System.out.println("Invoking getQuestionByIdForJava...");
        java.lang.Integer _getQuestionByIdForJava_questionId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.Question _getQuestionByIdForJava__return = port.getQuestionByIdForJava(_getQuestionByIdForJava_questionId);
        System.out.println("getQuestionByIdForJava.result=" + _getQuestionByIdForJava__return);


        }
        {
        System.out.println("Invoking getFirstLevelChildrenKnowledgePointByQuestionSummary...");
        java.lang.Integer _getFirstLevelChildrenKnowledgePointByQuestionSummary_userId = null;
        java.lang.Integer _getFirstLevelChildrenKnowledgePointByQuestionSummary_courseId = null;
        java.lang.Integer _getFirstLevelChildrenKnowledgePointByQuestionSummary_parentKnowledgePointId = null;
        java.lang.Integer _getFirstLevelChildrenKnowledgePointByQuestionSummary_maxLevel = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfKnowledgePointView _getFirstLevelChildrenKnowledgePointByQuestionSummary__return = port.getFirstLevelChildrenKnowledgePointByQuestionSummary(_getFirstLevelChildrenKnowledgePointByQuestionSummary_userId, _getFirstLevelChildrenKnowledgePointByQuestionSummary_courseId, _getFirstLevelChildrenKnowledgePointByQuestionSummary_parentKnowledgePointId, _getFirstLevelChildrenKnowledgePointByQuestionSummary_maxLevel);
        System.out.println("getFirstLevelChildrenKnowledgePointByQuestionSummary.result=" + _getFirstLevelChildrenKnowledgePointByQuestionSummary__return);


        }
        {
        System.out.println("Invoking getAllQuestionCategories...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetAllQuestionCategoriesRequest _getAllQuestionCategories_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory _getAllQuestionCategories__return = port.getAllQuestionCategories(_getAllQuestionCategories_request);
        System.out.println("getAllQuestionCategories.result=" + _getAllQuestionCategories__return);


        }
        {
        System.out.println("Invoking getQuestionCategoriesCheckOnline...");
        java.lang.Integer _getQuestionCategoriesCheckOnline_courseId = null;
        java.lang.Boolean _getQuestionCategoriesCheckOnline_supportOnline = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory _getQuestionCategoriesCheckOnline__return = port.getQuestionCategoriesCheckOnline(_getQuestionCategoriesCheckOnline_courseId, _getQuestionCategoriesCheckOnline_supportOnline);
        System.out.println("getQuestionCategoriesCheckOnline.result=" + _getQuestionCategoriesCheckOnline__return);


        }
        {
        System.out.println("Invoking searchCllectionQuestions...");
        java.lang.Integer _searchCllectionQuestions_bookVersionId = null;
        java.lang.String _searchCllectionQuestions_keyword = "";
        java.lang.Boolean _searchCllectionQuestions_onlineOnly = null;
        java.lang.Integer _searchCllectionQuestions_userId = null;
        java.lang.Integer _searchCllectionQuestions_pageNumber = null;
        java.lang.Integer _searchCllectionQuestions_numberRecords = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView _searchCllectionQuestions__return = port.searchCllectionQuestions(_searchCllectionQuestions_bookVersionId, _searchCllectionQuestions_keyword, _searchCllectionQuestions_onlineOnly, _searchCllectionQuestions_userId, _searchCllectionQuestions_pageNumber, _searchCllectionQuestions_numberRecords);
        System.out.println("searchCllectionQuestions.result=" + _searchCllectionQuestions__return);


        }
        {
        System.out.println("Invoking empty...");
        java.lang.String _empty_sessionId = "";
        java.lang.Integer _empty_userId = null;
        java.lang.Integer _empty_courseId = null;
        port.empty(_empty_sessionId, _empty_userId, _empty_courseId);


        }
        {
        System.out.println("Invoking getBookVersions...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetBookVersionsRequest _getBookVersions_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfBookVersion _getBookVersions__return = port.getBookVersions(_getBookVersions_request);
        System.out.println("getBookVersions.result=" + _getBookVersions__return);


        }
        {
        System.out.println("Invoking getBookVersionId...");
        java.lang.Integer _getBookVersionId_courseMappingId = null;
        java.lang.Integer _getBookVersionId__return = port.getBookVersionId(_getBookVersionId_courseMappingId);
        System.out.println("getBookVersionId.result=" + _getBookVersionId__return);


        }
        {
        System.out.println("Invoking getQuestionsByFilter...");
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint _getQuestionsByFilter_questionIds = null;
        java.lang.Boolean _getQuestionsByFilter_filterUnavaliableQuestions = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestion _getQuestionsByFilter__return = port.getQuestionsByFilter(_getQuestionsByFilter_questionIds, _getQuestionsByFilter_filterUnavaliableQuestions);
        System.out.println("getQuestionsByFilter.result=" + _getQuestionsByFilter__return);


        }
        {
        System.out.println("Invoking getOnlineQuestionsForKnowledgePoint...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetOnlineQuestionsForKnowledgePointRequest _getOnlineQuestionsForKnowledgePoint_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.OnlineQuestionSimplifiedFormatKnowledgePointList _getOnlineQuestionsForKnowledgePoint__return = port.getOnlineQuestionsForKnowledgePoint(_getOnlineQuestionsForKnowledgePoint_request);
        System.out.println("getOnlineQuestionsForKnowledgePoint.result=" + _getOnlineQuestionsForKnowledgePoint__return);


        }
        {
        System.out.println("Invoking getBookVersionsByCourse...");
        java.lang.Integer _getBookVersionsByCourse_courseId = null;
        java.lang.Boolean _getBookVersionsByCourse_isIncludeDeleted = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfBookVersion _getBookVersionsByCourse__return = port.getBookVersionsByCourse(_getBookVersionsByCourse_courseId, _getBookVersionsByCourse_isIncludeDeleted);
        System.out.println("getBookVersionsByCourse.result=" + _getBookVersionsByCourse__return);


        }
        {
        System.out.println("Invoking getCourseMapping...");
        java.lang.Integer _getCourseMapping_courseMappingId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.CourseMapping _getCourseMapping__return = port.getCourseMapping(_getCourseMapping_courseMappingId);
        System.out.println("getCourseMapping.result=" + _getCourseMapping__return);


        }
        {
        System.out.println("Invoking getClassRoomEvaluationDefaultSelected...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getClassRoomEvaluationDefaultSelected_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ClassRoomEvaluationDefaultSelected _getClassRoomEvaluationDefaultSelected__return = port.getClassRoomEvaluationDefaultSelected(_getClassRoomEvaluationDefaultSelected_request);
        System.out.println("getClassRoomEvaluationDefaultSelected.result=" + _getClassRoomEvaluationDefaultSelected__return);


        }
        {
        System.out.println("Invoking getQuestionsForJava...");
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint _getQuestionsForJava_questionIds = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestion _getQuestionsForJava__return = port.getQuestionsForJava(_getQuestionsForJava_questionIds);
        System.out.println("getQuestionsForJava.result=" + _getQuestionsForJava__return);


        }
        {
        System.out.println("Invoking getBookVersionChapterSections...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getBookVersionChapterSections_request = null;
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfintChapterSectionyHSjzk5H _getBookVersionChapterSections__return = port.getBookVersionChapterSections(_getBookVersionChapterSections_request);
        System.out.println("getBookVersionChapterSections.result=" + _getBookVersionChapterSections__return);


        }
        {
        System.out.println("Invoking getChapterSectionSimpleTreeByPage...");
        java.lang.Integer _getChapterSectionSimpleTreeByPage_courseMappingId = null;
        java.lang.Integer _getChapterSectionSimpleTreeByPage_pageindex = null;
        java.lang.Integer _getChapterSectionSimpleTreeByPage_pagesize = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree _getChapterSectionSimpleTreeByPage__return = port.getChapterSectionSimpleTreeByPage(_getChapterSectionSimpleTreeByPage_courseMappingId, _getChapterSectionSimpleTreeByPage_pageindex, _getChapterSectionSimpleTreeByPage_pagesize);
        System.out.println("getChapterSectionSimpleTreeByPage.result=" + _getChapterSectionSimpleTreeByPage__return);


        }
        {
        System.out.println("Invoking getExamSetQuestionDistribution...");
        java.lang.Integer _getExamSetQuestionDistribution_examSetId = null;
        java.lang.Boolean _getExamSetQuestionDistribution_bySection = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree _getExamSetQuestionDistribution__return = port.getExamSetQuestionDistribution(_getExamSetQuestionDistribution_examSetId, _getExamSetQuestionDistribution_bySection);
        System.out.println("getExamSetQuestionDistribution.result=" + _getExamSetQuestionDistribution__return);


        }
        {
        System.out.println("Invoking addQuestion...");
        java.lang.String _addQuestion_sessionId = "";
        java.lang.Integer _addQuestion_userId = null;
        java.lang.Integer _addQuestion_courseId = null;
        java.lang.Integer _addQuestion_questionId = null;
        java.lang.Integer _addQuestion_bookversionId = null;
        java.lang.String _addQuestion__return = port.addQuestion(_addQuestion_sessionId, _addQuestion_userId, _addQuestion_courseId, _addQuestion_questionId, _addQuestion_bookversionId);
        System.out.println("addQuestion.result=" + _addQuestion__return);


        }
        {
        System.out.println("Invoking getBookVersionByUserId...");
        java.lang.Integer _getBookVersionByUserId_userId = null;
        java.lang.Integer _getBookVersionByUserId_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.BookVersion _getBookVersionByUserId__return = port.getBookVersionByUserId(_getBookVersionByUserId_userId, _getBookVersionByUserId_courseId);
        System.out.println("getBookVersionByUserId.result=" + _getBookVersionByUserId__return);


        }
        {
        System.out.println("Invoking getAllBookVersions...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetBookVersionsRequest _getAllBookVersions_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfBookVersion _getAllBookVersions__return = port.getAllBookVersions(_getAllBookVersions_request);
        System.out.println("getAllBookVersions.result=" + _getAllBookVersions__return);


        }
        {
        System.out.println("Invoking getKnowledgePointSimpleTree...");
        java.lang.Integer _getKnowledgePointSimpleTree_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree _getKnowledgePointSimpleTree__return = port.getKnowledgePointSimpleTree(_getKnowledgePointSimpleTree_courseId);
        System.out.println("getKnowledgePointSimpleTree.result=" + _getKnowledgePointSimpleTree__return);


        }
        {
        System.out.println("Invoking getQuestionReportModel...");
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint _getQuestionReportModel_questionId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionReportModel _getQuestionReportModel__return = port.getQuestionReportModel(_getQuestionReportModel_questionId);
        System.out.println("getQuestionReportModel.result=" + _getQuestionReportModel__return);


        }
        {
        System.out.println("Invoking getRootQuestionCategoriesCheckOnline...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionCategoriesCheckOnlineRequest _getRootQuestionCategoriesCheckOnline_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory _getRootQuestionCategoriesCheckOnline__return = port.getRootQuestionCategoriesCheckOnline(_getRootQuestionCategoriesCheckOnline_request);
        System.out.println("getRootQuestionCategoriesCheckOnline.result=" + _getRootQuestionCategoriesCheckOnline__return);


        }
        {
        System.out.println("Invoking addMultipleQuestion...");
        java.lang.String _addMultipleQuestion_sessionId = "";
        java.lang.Integer _addMultipleQuestion_userId = null;
        java.lang.Integer _addMultipleQuestion_courseId = null;
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _addMultipleQuestion_questionIds = null;
        java.lang.Integer _addMultipleQuestion_bookversionId = null;
        java.lang.String _addMultipleQuestion__return = port.addMultipleQuestion(_addMultipleQuestion_sessionId, _addMultipleQuestion_userId, _addMultipleQuestion_courseId, _addMultipleQuestion_questionIds, _addMultipleQuestion_bookversionId);
        System.out.println("addMultipleQuestion.result=" + _addMultipleQuestion__return);


        }
        {
        System.out.println("Invoking getQuestionsFromSections...");
        java.lang.Integer _getQuestionsFromSections_courseMappingId = null;
        java.lang.Boolean _getQuestionsFromSections_onlineOnly = null;
        java.lang.Integer _getQuestionsFromSections_questionLevel = null;
        java.lang.Integer _getQuestionsFromSections_questionCategory = null;
        java.lang.Integer _getQuestionsFromSections_pageNumber = null;
        java.lang.Integer _getQuestionsFromSections_numberRecords = null;
        java.lang.Integer _getQuestionsFromSections_sectionId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView _getQuestionsFromSections__return = port.getQuestionsFromSections(_getQuestionsFromSections_courseMappingId, _getQuestionsFromSections_onlineOnly, _getQuestionsFromSections_questionLevel, _getQuestionsFromSections_questionCategory, _getQuestionsFromSections_pageNumber, _getQuestionsFromSections_numberRecords, _getQuestionsFromSections_sectionId);
        System.out.println("getQuestionsFromSections.result=" + _getQuestionsFromSections__return);


        }
        {
        System.out.println("Invoking getChapterSection...");
        java.lang.Integer _getChapterSection_sectionId = null;
        java.lang.Integer _getChapterSection_courseMappingId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ChapterSectionView _getChapterSection__return = port.getChapterSection(_getChapterSection_sectionId, _getChapterSection_courseMappingId);
        System.out.println("getChapterSection.result=" + _getChapterSection__return);


        }
        {
        System.out.println("Invoking getCourseMappingsByCourseId...");
        java.lang.Integer _getCourseMappingsByCourseId_userId = null;
        java.lang.Integer _getCourseMappingsByCourseId_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfCourseMapping _getCourseMappingsByCourseId__return = port.getCourseMappingsByCourseId(_getCourseMappingsByCourseId_userId, _getCourseMappingsByCourseId_courseId);
        System.out.println("getCourseMappingsByCourseId.result=" + _getCourseMappingsByCourseId__return);


        }
        {
        System.out.println("Invoking getExamUsageRulerView...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetExamUsageRulerViewRequest _getExamUsageRulerView_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ExamUsageRulerView _getExamUsageRulerView__return = port.getExamUsageRulerView(_getExamUsageRulerView_request);
        System.out.println("getExamUsageRulerView.result=" + _getExamUsageRulerView__return);


        }
        {
        System.out.println("Invoking getQuestionDisplayType...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getQuestionDisplayType_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.QuestionDisplayType _getQuestionDisplayType__return = port.getQuestionDisplayType(_getQuestionDisplayType_request);
        System.out.println("getQuestionDisplayType.result=" + _getQuestionDisplayType__return);


        }
        {
        System.out.println("Invoking checkSCPQuestion...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.SCPQuestionRequest _checkSCPQuestion_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.CheckSCPQuestionView _checkSCPQuestion__return = port.checkSCPQuestion(_checkSCPQuestion_request);
        System.out.println("checkSCPQuestion.result=" + _checkSCPQuestion__return);


        }
        {
        System.out.println("Invoking getSCPQuestionDetails...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.SCPQuestionRequest _getSCPQuestionDetails_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.SCPQuestionDetailView _getSCPQuestionDetails__return = port.getSCPQuestionDetails(_getSCPQuestionDetails_request);
        System.out.println("getSCPQuestionDetails.result=" + _getSCPQuestionDetails__return);


        }
        {
        System.out.println("Invoking getPreviewConfigSession...");
        java.lang.String _getPreviewConfigSession_sessionId = "";
        java.lang.Boolean _getPreviewConfigSession_online = null;
        java.lang.String _getPreviewConfigSession__return = port.getPreviewConfigSession(_getPreviewConfigSession_sessionId, _getPreviewConfigSession_online);
        System.out.println("getPreviewConfigSession.result=" + _getPreviewConfigSession__return);


        }
        {
        System.out.println("Invoking getQuestions...");
        wcf.tikuservice.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint _getQuestions_questionIds = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestion _getQuestions__return = port.getQuestions(_getQuestions_questionIds);
        System.out.println("getQuestions.result=" + _getQuestions__return);


        }
        {
        System.out.println("Invoking generateOneClickTestPaperQuestions...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.OneClickTestPaperRequest _generateOneClickTestPaperQuestions_oneClickTestPaperRequest = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.OneClickTestPaperResultView _generateOneClickTestPaperQuestions__return = port.generateOneClickTestPaperQuestions(_generateOneClickTestPaperQuestions_oneClickTestPaperRequest);
        System.out.println("generateOneClickTestPaperQuestions.result=" + _generateOneClickTestPaperQuestions__return);


        }
        {
        System.out.println("Invoking getQuestionLabels...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getQuestionLabels_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionLabel _getQuestionLabels__return = port.getQuestionLabels(_getQuestionLabels_request);
        System.out.println("getQuestionLabels.result=" + _getQuestionLabels__return);


        }
        {
        System.out.println("Invoking getAllCourseMappings...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfCourseMapping _getAllCourseMappings__return = port.getAllCourseMappings();
        System.out.println("getAllCourseMappings.result=" + _getAllCourseMappings__return);


        }
        {
        System.out.println("Invoking getFirstLevelChildrenKnowledgePointByQuestionSummaryV2...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.KnowledgePointQuestionRequest _getFirstLevelChildrenKnowledgePointByQuestionSummaryV2_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfKnowledgePointView _getFirstLevelChildrenKnowledgePointByQuestionSummaryV2__return = port.getFirstLevelChildrenKnowledgePointByQuestionSummaryV2(_getFirstLevelChildrenKnowledgePointByQuestionSummaryV2_request);
        System.out.println("getFirstLevelChildrenKnowledgePointByQuestionSummaryV2.result=" + _getFirstLevelChildrenKnowledgePointByQuestionSummaryV2__return);


        }
        {
        System.out.println("Invoking getQuestionsFromKnowledgePoints...");
        java.lang.Integer _getQuestionsFromKnowledgePoints_bookVersionId = null;
        java.lang.Boolean _getQuestionsFromKnowledgePoints_onlineOnly = null;
        java.lang.Integer _getQuestionsFromKnowledgePoints_questionLevel = null;
        java.lang.Integer _getQuestionsFromKnowledgePoints_questionCategory = null;
        java.lang.Integer _getQuestionsFromKnowledgePoints_pageNumber = null;
        java.lang.Integer _getQuestionsFromKnowledgePoints_numberRecords = null;
        java.lang.Integer _getQuestionsFromKnowledgePoints_knowledgePointId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.QuestionListView _getQuestionsFromKnowledgePoints__return = port.getQuestionsFromKnowledgePoints(_getQuestionsFromKnowledgePoints_bookVersionId, _getQuestionsFromKnowledgePoints_onlineOnly, _getQuestionsFromKnowledgePoints_questionLevel, _getQuestionsFromKnowledgePoints_questionCategory, _getQuestionsFromKnowledgePoints_pageNumber, _getQuestionsFromKnowledgePoints_numberRecords, _getQuestionsFromKnowledgePoints_knowledgePointId);
        System.out.println("getQuestionsFromKnowledgePoints.result=" + _getQuestionsFromKnowledgePoints__return);


        }
        {
        System.out.println("Invoking getCoursePreKnowledgePoints...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getCoursePreKnowledgePoints_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.PreKnowledgePointList _getCoursePreKnowledgePoints__return = port.getCoursePreKnowledgePoints(_getCoursePreKnowledgePoints_request);
        System.out.println("getCoursePreKnowledgePoints.result=" + _getCoursePreKnowledgePoints__return);


        }
        {
        System.out.println("Invoking getParentChapterSections...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getParentChapterSections_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfChapterSection _getParentChapterSections__return = port.getParentChapterSections(_getParentChapterSections_request);
        System.out.println("getParentChapterSections.result=" + _getParentChapterSections__return);


        }
        {
        System.out.println("Invoking getQuestionCategories...");
        java.lang.Integer _getQuestionCategories_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory _getQuestionCategories__return = port.getQuestionCategories(_getQuestionCategories_courseId);
        System.out.println("getQuestionCategories.result=" + _getQuestionCategories__return);


        }
        {
        System.out.println("Invoking removePreviewConfigSession...");
        java.lang.String _removePreviewConfigSession_sessionId = "";
        java.lang.Boolean _removePreviewConfigSession_online = null;
        port.removePreviewConfigSession(_removePreviewConfigSession_sessionId, _removePreviewConfigSession_online);


        }
        {
        System.out.println("Invoking getChapterSectionSimpleTree...");
        java.lang.Integer _getChapterSectionSimpleTree_courseMappingId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk.SimpleTree _getChapterSectionSimpleTree__return = port.getChapterSectionSimpleTree(_getChapterSectionSimpleTree_courseMappingId);
        System.out.println("getChapterSectionSimpleTree.result=" + _getChapterSectionSimpleTree__return);


        }
        {
        System.out.println("Invoking getChapterSections...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getChapterSections_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ChapterSectionList _getChapterSections__return = port.getChapterSections(_getChapterSections_request);
        System.out.println("getChapterSections.result=" + _getChapterSections__return);


        }
        {
        System.out.println("Invoking getAllExamUsageRulers...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfExamUsageRuler _getAllExamUsageRulers__return = port.getAllExamUsageRulers();
        System.out.println("getAllExamUsageRulers.result=" + _getAllExamUsageRulers__return);


        }
        {
        System.out.println("Invoking getSimilarQuestionList...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.IdRequest _getSimilarQuestionList_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.SimilarQuestionList _getSimilarQuestionList__return = port.getSimilarQuestionList(_getSimilarQuestionList_request);
        System.out.println("getSimilarQuestionList.result=" + _getSimilarQuestionList__return);


        }
        {
        System.out.println("Invoking getBookVersion...");
        java.lang.Integer _getBookVersion_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfBookVersion _getBookVersion__return = port.getBookVersion(_getBookVersion_courseId);
        System.out.println("getBookVersion.result=" + _getBookVersion__return);


        }
        {
        System.out.println("Invoking getQuestionStatistics...");
        java.lang.Integer _getQuestionStatistics_questionId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.QuestionStatistics _getQuestionStatistics__return = port.getQuestionStatistics(_getQuestionStatistics_questionId);
        System.out.println("getQuestionStatistics.result=" + _getQuestionStatistics__return);


        }
        {
        System.out.println("Invoking getZujuanBasketStatistics...");
        java.lang.String _getZujuanBasketStatistics_sessionId = "";
        java.lang.Integer _getZujuanBasketStatistics_userId = null;
        java.lang.Integer _getZujuanBasketStatistics_courseId = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_exam.ArrayOfZujuanBasketQuestionCategoryStatisticsView _getZujuanBasketStatistics__return = port.getZujuanBasketStatistics(_getZujuanBasketStatistics_sessionId, _getZujuanBasketStatistics_userId, _getZujuanBasketStatistics_courseId);
        System.out.println("getZujuanBasketStatistics.result=" + _getZujuanBasketStatistics__return);


        }
        {
        System.out.println("Invoking getQuestionStatisticsList...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionStatisticsListRequest _getQuestionStatisticsList_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionStatistics _getQuestionStatisticsList__return = port.getQuestionStatisticsList(_getQuestionStatisticsList_request);
        System.out.println("getQuestionStatisticsList.result=" + _getQuestionStatisticsList__return);


        }
        {
        System.out.println("Invoking getHasQuestionBookVersion...");
        java.lang.Integer _getHasQuestionBookVersion_userId = null;
        java.lang.Integer _getHasQuestionBookVersion_courseId = null;
        java.lang.String _getHasQuestionBookVersion_includeSpecifyBookVersion = "";
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.ArrayOfBookVersionView _getHasQuestionBookVersion__return = port.getHasQuestionBookVersion(_getHasQuestionBookVersion_userId, _getHasQuestionBookVersion_courseId, _getHasQuestionBookVersion_includeSpecifyBookVersion);
        System.out.println("getHasQuestionBookVersion.result=" + _getHasQuestionBookVersion__return);


        }
        {
        System.out.println("Invoking getGetQuestionDisplayTypes...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionDisplayType _getGetQuestionDisplayTypes__return = port.getGetQuestionDisplayTypes();
        System.out.println("getGetQuestionDisplayTypes.result=" + _getGetQuestionDisplayTypes__return);


        }
        {
        System.out.println("Invoking getQuestionCategoriesCheckOnlineNew...");
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model_tiku.GetQuestionCategoriesCheckOnlineRequest _getQuestionCategoriesCheckOnlineNew_request = null;
        wcf.tikuservice.org.datacontract.schemas._2004._07.motk_model.ArrayOfQuestionCategory _getQuestionCategoriesCheckOnlineNew__return = port.getQuestionCategoriesCheckOnlineNew(_getQuestionCategoriesCheckOnlineNew_request);
        System.out.println("getQuestionCategoriesCheckOnlineNew.result=" + _getQuestionCategoriesCheckOnlineNew__return);


        }

        System.exit(0);
    }

}
