package wcf.wechataccessservice.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-29T14:43:19.193+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IWeChatAccessService")
@XmlSeeAlso({wcf.wechataccessservice.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.ObjectFactory.class, ObjectFactory.class, wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.ObjectFactory.class, wcf.wechataccessservice.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_wechat.ObjectFactory.class})
public interface IWeChatAccessService {

    @WebMethod(operationName = "GetAuthorizationInfoV2", action = "http://tempuri.org/IWeChatAccessService/GetAuthorizationInfoV2")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetAuthorizationInfoV2", output = "http://tempuri.org/IWeChatAccessService/GetAuthorizationInfoV2Response")
    @RequestWrapper(localName = "GetAuthorizationInfoV2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAuthorizationInfoV2")
    @ResponseWrapper(localName = "GetAuthorizationInfoV2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAuthorizationInfoV2Response")
    @WebResult(name = "GetAuthorizationInfoV2Result", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatAuthorizationInfoView getAuthorizationInfoV2(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatAuthorizationInfoRequest request
    );

    @WebMethod(operationName = "CreateMenu", action = "http://tempuri.org/IWeChatAccessService/CreateMenu")
    @Action(input = "http://tempuri.org/IWeChatAccessService/CreateMenu", output = "http://tempuri.org/IWeChatAccessService/CreateMenuResponse")
    @RequestWrapper(localName = "CreateMenu", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateMenu")
    @ResponseWrapper(localName = "CreateMenuResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateMenuResponse")
    @WebResult(name = "CreateMenuResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.ResultMessage createMenu(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.CreateWeChatMenuRequest request
    );

    @WebMethod(operationName = "GetShortUrl", action = "http://tempuri.org/IWeChatAccessService/GetShortUrl")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetShortUrl", output = "http://tempuri.org/IWeChatAccessService/GetShortUrlResponse")
    @RequestWrapper(localName = "GetShortUrl", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetShortUrl")
    @ResponseWrapper(localName = "GetShortUrlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetShortUrlResponse")
    @WebResult(name = "GetShortUrlResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getShortUrl(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatPayRequestBase request
    );

    @WebMethod(operationName = "GetNewsItemResult", action = "http://tempuri.org/IWeChatAccessService/GetNewsItemResult")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetNewsItemResult", output = "http://tempuri.org/IWeChatAccessService/GetNewsItemResultResponse")
    @RequestWrapper(localName = "GetNewsItemResult", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNewsItemResult")
    @ResponseWrapper(localName = "GetNewsItemResultResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNewsItemResultResponse")
    @WebResult(name = "GetNewsItemResultResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.NewsItemRequestResult getNewsItemResult(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_wechat.GetMaterialRequest request
    );

    @WebMethod(operationName = "SendCustomMessage", action = "http://tempuri.org/IWeChatAccessService/SendCustomMessage")
    @Action(input = "http://tempuri.org/IWeChatAccessService/SendCustomMessage", output = "http://tempuri.org/IWeChatAccessService/SendCustomMessageResponse")
    @RequestWrapper(localName = "SendCustomMessage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCustomMessage")
    @ResponseWrapper(localName = "SendCustomMessageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCustomMessageResponse")
    @WebResult(name = "SendCustomMessageResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean sendCustomMessage(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.SendCustomMessageRequest request
    );

    @WebMethod(operationName = "SendPayRequest", action = "http://tempuri.org/IWeChatAccessService/SendPayRequest")
    @Action(input = "http://tempuri.org/IWeChatAccessService/SendPayRequest", output = "http://tempuri.org/IWeChatAccessService/SendPayRequestResponse")
    @RequestWrapper(localName = "SendPayRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPayRequest")
    @ResponseWrapper(localName = "SendPayRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendPayRequestResponse")
    @WebResult(name = "SendPayRequestResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendPayRequest(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.SendWeChatPayRequest request
    );

    @WebMethod(operationName = "GetWechatUserInfoV2", action = "http://tempuri.org/IWeChatAccessService/GetWechatUserInfoV2")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetWechatUserInfoV2", output = "http://tempuri.org/IWeChatAccessService/GetWechatUserInfoV2Response")
    @RequestWrapper(localName = "GetWechatUserInfoV2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWechatUserInfoV2")
    @ResponseWrapper(localName = "GetWechatUserInfoV2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWechatUserInfoV2Response")
    @WebResult(name = "GetWechatUserInfoV2Result", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatUserInfoView getWechatUserInfoV2(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatUserInfoRequest request
    );

    @WebMethod(operationName = "ReversePayRequest", action = "http://tempuri.org/IWeChatAccessService/ReversePayRequest")
    @Action(input = "http://tempuri.org/IWeChatAccessService/ReversePayRequest", output = "http://tempuri.org/IWeChatAccessService/ReversePayRequestResponse")
    @RequestWrapper(localName = "ReversePayRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReversePayRequest")
    @ResponseWrapper(localName = "ReversePayRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReversePayRequestResponse")
    @WebResult(name = "ReversePayRequestResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String reversePayRequest(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatPayRequestBase request
    );

    @WebMethod(operationName = "Transfer", action = "http://tempuri.org/IWeChatAccessService/Transfer")
    @Action(input = "http://tempuri.org/IWeChatAccessService/Transfer", output = "http://tempuri.org/IWeChatAccessService/TransferResponse")
    @RequestWrapper(localName = "Transfer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Transfer")
    @ResponseWrapper(localName = "TransferResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferResponse")
    @WebResult(name = "TransferResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.WechatTransferResponse transfer(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_wechat.WechatTransferRequest request
    );

    @WebMethod(operationName = "GetWechatUserInfo", action = "http://tempuri.org/IWeChatAccessService/GetWechatUserInfo")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetWechatUserInfo", output = "http://tempuri.org/IWeChatAccessService/GetWechatUserInfoResponse")
    @RequestWrapper(localName = "GetWechatUserInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWechatUserInfo")
    @ResponseWrapper(localName = "GetWechatUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWechatUserInfoResponse")
    @WebResult(name = "GetWechatUserInfoResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatUserInfoView getWechatUserInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatUserInfoRequest request
    );

    @WebMethod(operationName = "ShortUrl", action = "http://tempuri.org/IWeChatAccessService/ShortUrl")
    @Action(input = "http://tempuri.org/IWeChatAccessService/ShortUrl", output = "http://tempuri.org/IWeChatAccessService/ShortUrlResponse")
    @RequestWrapper(localName = "ShortUrl", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ShortUrl")
    @ResponseWrapper(localName = "ShortUrlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ShortUrlResponse")
    @WebResult(name = "ShortUrlResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.ShortUrlResult shortUrl(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.ShortUrlRequest request
    );

    @WebMethod(operationName = "GetWeChatTicket", action = "http://tempuri.org/IWeChatAccessService/GetWeChatTicket")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetWeChatTicket", output = "http://tempuri.org/IWeChatAccessService/GetWeChatTicketResponse")
    @RequestWrapper(localName = "GetWeChatTicket", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWeChatTicket")
    @ResponseWrapper(localName = "GetWeChatTicketResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWeChatTicketResponse")
    @WebResult(name = "GetWeChatTicketResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatTicketInfoView getWeChatTicket(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatTicketRequest request
    );

    @WebMethod(operationName = "GetAuthorizationUrl", action = "http://tempuri.org/IWeChatAccessService/GetAuthorizationUrl")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetAuthorizationUrl", output = "http://tempuri.org/IWeChatAccessService/GetAuthorizationUrlResponse")
    @RequestWrapper(localName = "GetAuthorizationUrl", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAuthorizationUrl")
    @ResponseWrapper(localName = "GetAuthorizationUrlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAuthorizationUrlResponse")
    @WebResult(name = "GetAuthorizationUrlResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetAuthorizeUrlView getAuthorizationUrl(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetAuthorizeUrlRequest request
    );

    @WebMethod(operationName = "TemplateMesageSend", action = "http://tempuri.org/IWeChatAccessService/TemplateMesageSend")
    @Action(input = "http://tempuri.org/IWeChatAccessService/TemplateMesageSend", output = "http://tempuri.org/IWeChatAccessService/TemplateMesageSendResponse")
    @RequestWrapper(localName = "TemplateMesageSend", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TemplateMesageSend")
    @ResponseWrapper(localName = "TemplateMesageSendResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TemplateMesageSendResponse")
    @WebResult(name = "TemplateMesageSendResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean templateMesageSend(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.TemplateMesageSendRequest request
    );

    @WebMethod(operationName = "ProcessRequest", action = "http://tempuri.org/IWeChatAccessService/ProcessRequest")
    @Action(input = "http://tempuri.org/IWeChatAccessService/ProcessRequest", output = "http://tempuri.org/IWeChatAccessService/ProcessRequestResponse")
    @RequestWrapper(localName = "ProcessRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessRequest")
    @ResponseWrapper(localName = "ProcessRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessRequestResponse")
    @WebResult(name = "ProcessRequestResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatResponseView processRequest(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatProcessRequest request
    );

    @WebMethod(operationName = "CreateQrUrl", action = "http://tempuri.org/IWeChatAccessService/CreateQrUrl")
    @Action(input = "http://tempuri.org/IWeChatAccessService/CreateQrUrl", output = "http://tempuri.org/IWeChatAccessService/CreateQrUrlResponse")
    @RequestWrapper(localName = "CreateQrUrl", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQrUrl")
    @ResponseWrapper(localName = "CreateQrUrlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQrUrlResponse")
    @WebResult(name = "CreateQrUrlResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String createQrUrl(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.CreateQrRequest request
    );

    @WebMethod(operationName = "GetEncryptMsg", action = "http://tempuri.org/IWeChatAccessService/GetEncryptMsg")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetEncryptMsg", output = "http://tempuri.org/IWeChatAccessService/GetEncryptMsgResponse")
    @RequestWrapper(localName = "GetEncryptMsg", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEncryptMsg")
    @ResponseWrapper(localName = "GetEncryptMsgResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEncryptMsgResponse")
    @WebResult(name = "GetEncryptMsgResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatEncryptView getEncryptMsg(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatEncryptRequest request
    );

    @WebMethod(operationName = "SendTextMessage", action = "http://tempuri.org/IWeChatAccessService/SendTextMessage")
    @Action(input = "http://tempuri.org/IWeChatAccessService/SendTextMessage", output = "http://tempuri.org/IWeChatAccessService/SendTextMessageResponse")
    @RequestWrapper(localName = "SendTextMessage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendTextMessage")
    @ResponseWrapper(localName = "SendTextMessageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendTextMessageResponse")
    @WebResult(name = "SendTextMessageResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.ResultMessage sendTextMessage(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.SendWeChatTextMessageRequest request
    );

    @WebMethod(operationName = "GetAccessToken", action = "http://tempuri.org/IWeChatAccessService/GetAccessToken")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetAccessToken", output = "http://tempuri.org/IWeChatAccessService/GetAccessTokenResponse")
    @RequestWrapper(localName = "GetAccessToken", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccessToken")
    @ResponseWrapper(localName = "GetAccessTokenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccessTokenResponse")
    @WebResult(name = "GetAccessTokenResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatAccessTokenView getAccessToken(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatAccessTokenRequest request
    );

    @WebMethod(operationName = "GetAuthorizationInfo", action = "http://tempuri.org/IWeChatAccessService/GetAuthorizationInfo")
    @Action(input = "http://tempuri.org/IWeChatAccessService/GetAuthorizationInfo", output = "http://tempuri.org/IWeChatAccessService/GetAuthorizationInfoResponse")
    @RequestWrapper(localName = "GetAuthorizationInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAuthorizationInfo")
    @ResponseWrapper(localName = "GetAuthorizationInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAuthorizationInfoResponse")
    @WebResult(name = "GetAuthorizationInfoResult", targetNamespace = "http://tempuri.org/")
    public wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatAuthorizationInfoView getAuthorizationInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatAuthorizationInfoRequest request
    );
}
