
package wcf.wechataccessservice.org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-29T14:43:19.127+08:00
 * Generated source version: 3.2.4
 *
 */
public final class IWeChatAccessService_BasicHttpBindingIWeChatAccessService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WeChatAccessService");

    private IWeChatAccessService_BasicHttpBindingIWeChatAccessService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WeChatAccessService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WeChatAccessService ss = new WeChatAccessService(wsdlURL, SERVICE_NAME);
        IWeChatAccessService port = ss.getBasicHttpBindingIWeChatAccessService();

        {
        System.out.println("Invoking getAuthorizationInfoV2...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatAuthorizationInfoRequest _getAuthorizationInfoV2_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatAuthorizationInfoView _getAuthorizationInfoV2__return = port.getAuthorizationInfoV2(_getAuthorizationInfoV2_request);
        System.out.println("getAuthorizationInfoV2.result=" + _getAuthorizationInfoV2__return);


        }
        {
        System.out.println("Invoking createMenu...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.CreateWeChatMenuRequest _createMenu_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.ResultMessage _createMenu__return = port.createMenu(_createMenu_request);
        System.out.println("createMenu.result=" + _createMenu__return);


        }
        {
        System.out.println("Invoking getShortUrl...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatPayRequestBase _getShortUrl_request = null;
        java.lang.String _getShortUrl__return = port.getShortUrl(_getShortUrl_request);
        System.out.println("getShortUrl.result=" + _getShortUrl__return);


        }
        {
        System.out.println("Invoking getNewsItemResult...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_wechat.GetMaterialRequest _getNewsItemResult_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.NewsItemRequestResult _getNewsItemResult__return = port.getNewsItemResult(_getNewsItemResult_request);
        System.out.println("getNewsItemResult.result=" + _getNewsItemResult__return);


        }
        {
        System.out.println("Invoking sendCustomMessage...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.SendCustomMessageRequest _sendCustomMessage_request = null;
        java.lang.Boolean _sendCustomMessage__return = port.sendCustomMessage(_sendCustomMessage_request);
        System.out.println("sendCustomMessage.result=" + _sendCustomMessage__return);


        }
        {
        System.out.println("Invoking sendPayRequest...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.SendWeChatPayRequest _sendPayRequest_request = null;
        java.lang.String _sendPayRequest__return = port.sendPayRequest(_sendPayRequest_request);
        System.out.println("sendPayRequest.result=" + _sendPayRequest__return);


        }
        {
        System.out.println("Invoking getWechatUserInfoV2...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatUserInfoRequest _getWechatUserInfoV2_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatUserInfoView _getWechatUserInfoV2__return = port.getWechatUserInfoV2(_getWechatUserInfoV2_request);
        System.out.println("getWechatUserInfoV2.result=" + _getWechatUserInfoV2__return);


        }
        {
        System.out.println("Invoking reversePayRequest...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatPayRequestBase _reversePayRequest_request = null;
        java.lang.String _reversePayRequest__return = port.reversePayRequest(_reversePayRequest_request);
        System.out.println("reversePayRequest.result=" + _reversePayRequest__return);


        }
        {
        System.out.println("Invoking transfer...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_wechat.WechatTransferRequest _transfer_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.WechatTransferResponse _transfer__return = port.transfer(_transfer_request);
        System.out.println("transfer.result=" + _transfer__return);


        }
        {
        System.out.println("Invoking getWechatUserInfo...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatUserInfoRequest _getWechatUserInfo_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatUserInfoView _getWechatUserInfo__return = port.getWechatUserInfo(_getWechatUserInfo_request);
        System.out.println("getWechatUserInfo.result=" + _getWechatUserInfo__return);


        }
        {
        System.out.println("Invoking shortUrl...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.ShortUrlRequest _shortUrl_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.ShortUrlResult _shortUrl__return = port.shortUrl(_shortUrl_request);
        System.out.println("shortUrl.result=" + _shortUrl__return);


        }
        {
        System.out.println("Invoking getWeChatTicket...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatTicketRequest _getWeChatTicket_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatTicketInfoView _getWeChatTicket__return = port.getWeChatTicket(_getWeChatTicket_request);
        System.out.println("getWeChatTicket.result=" + _getWeChatTicket__return);


        }
        {
        System.out.println("Invoking getAuthorizationUrl...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetAuthorizeUrlRequest _getAuthorizationUrl_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetAuthorizeUrlView _getAuthorizationUrl__return = port.getAuthorizationUrl(_getAuthorizationUrl_request);
        System.out.println("getAuthorizationUrl.result=" + _getAuthorizationUrl__return);


        }
        {
        System.out.println("Invoking templateMesageSend...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.TemplateMesageSendRequest _templateMesageSend_request = null;
        java.lang.Boolean _templateMesageSend__return = port.templateMesageSend(_templateMesageSend_request);
        System.out.println("templateMesageSend.result=" + _templateMesageSend__return);


        }
        {
        System.out.println("Invoking processRequest...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatProcessRequest _processRequest_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatResponseView _processRequest__return = port.processRequest(_processRequest_request);
        System.out.println("processRequest.result=" + _processRequest__return);


        }
        {
        System.out.println("Invoking createQrUrl...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.CreateQrRequest _createQrUrl_request = null;
        java.lang.String _createQrUrl__return = port.createQrUrl(_createQrUrl_request);
        System.out.println("createQrUrl.result=" + _createQrUrl__return);


        }
        {
        System.out.println("Invoking getEncryptMsg...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatEncryptRequest _getEncryptMsg_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatEncryptView _getEncryptMsg__return = port.getEncryptMsg(_getEncryptMsg_request);
        System.out.println("getEncryptMsg.result=" + _getEncryptMsg__return);


        }
        {
        System.out.println("Invoking sendTextMessage...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.SendWeChatTextMessageRequest _sendTextMessage_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model.ResultMessage _sendTextMessage__return = port.sendTextMessage(_sendTextMessage_request);
        System.out.println("sendTextMessage.result=" + _sendTextMessage__return);


        }
        {
        System.out.println("Invoking getAccessToken...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatAccessTokenRequest _getAccessToken_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatAccessTokenView _getAccessToken__return = port.getAccessToken(_getAccessToken_request);
        System.out.println("getAccessToken.result=" + _getAccessToken__return);


        }
        {
        System.out.println("Invoking getAuthorizationInfo...");
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.GetWeChatAuthorizationInfoRequest _getAuthorizationInfo_request = null;
        wcf.wechataccessservice.org.datacontract.schemas._2004._07.motk_model_thirdparty.WeChatAuthorizationInfoView _getAuthorizationInfo__return = port.getAuthorizationInfo(_getAuthorizationInfo_request);
        System.out.println("getAuthorizationInfo.result=" + _getAuthorizationInfo__return);


        }

        System.exit(0);
    }

}
